// Template agreements producers can send to artists from the Contracts page.
// The chosen template's default terms pre-fill the form; the producer can edit before sending.
export const CONTRACT_TEMPLATES = [
  {
    id: "beat_lease",
    name: "Beat Lease (Non-Exclusive)",
    description: "Artist licenses the beat for a commercial release — you keep ownership and can re-license it.",
    showDeal: true,
    defaultTerms: `1. GRANT OF LICENSE. Producer grants Artist a non-exclusive, non-transferable license to record upon, reproduce, distribute, and commercially exploit a recording incorporating the beat listed above ("Recording").

2. SCOPE. Artist may distribute up to 10,000 copies of the Recording (physical + digital downloads) and may monetize the Recording on all streaming platforms without a stream cap. Music videos are permitted. Use in television, film, or advertising requires separate written approval.

3. OWNERSHIP. Producer retains full ownership of the beat and all rights in the underlying composition and master, and may continue to license it to other artists.

4. CREDIT. Artist shall credit Producer on all releases as "Prod. by [Producer]".

5. FEE. Artist shall pay Producer the fee listed above, due upon signing of this agreement. The license is effective upon receipt of payment.

6. TERM. This license runs for ten (10) years from the date of signing, unless terminated earlier for breach.`,
  },
  {
    id: "exclusive_rights",
    name: "Exclusive Rights Transfer",
    description: "Artist buys the beat outright — it comes off the market and becomes theirs.",
    showDeal: true,
    defaultTerms: `1. TRANSFER OF RIGHTS. Upon receipt of the fee listed above, Producer transfers to Artist all right, title, and interest in the beat listed above, including the right to modify, reproduce, distribute, and commercially exploit it worldwide, in perpetuity, to the fullest extent permitted by law.

2. RETAINED WRITER'S SHARE. Producer retains Producer's writer's share of the underlying composition and a publishing share of 50% of the composition. All rights in the master recording transfer to Artist.

3. REMOVAL FROM SALE. Producer shall immediately cease licensing or selling the beat to any other party upon signing.

4. CREDIT. Artist shall credit Producer on all releases as "Prod. by [Producer]".

5. FEE. The fee listed above is due upon signing. The transfer is effective upon receipt of payment.

6. WARRANTIES. Each party warrants they have the authority to enter this agreement. Producer warrants the beat is an original work not sampled from any uncleared third-party material.`,
  },
  {
    id: "collab_split",
    name: "Producer Collab / Split Agreement",
    description: "You and the artist make the record together — ownership, publishing, and revenue split agreed up front.",
    showDeal: true,
    defaultTerms: `1. COLLABORATION. Producer and Artist ("the Parties") agree to create the work listed above ("the Work") jointly, with Producer providing production and Artist providing vocals/performance.

2. MASTER OWNERSHIP. The Parties own the master recording of the Work as follows: Producer 50% / Artist 50%, unless otherwise stated in the Terms.

3. PUBLISHING. Publishing on the underlying composition is split: Producer 50% / Artist 50%. Each Party retains their own writer's share. Each Party shall register their share with their performing rights organization.

4. REVENUE. All net revenue generated by the Work (streaming, sync, downloads, licensing) shall be split in proportion to the ownership split above. Settlements shall occur quarterly.

5. EXPLOITATION. Either Party may pitch the Work for sync or licensing with the other Party's consent, which shall not be unreasonably withheld.

6. CREDIT. The Work shall be credited to both Parties on all releases.`,
  },
  {
    id: "nda",
    name: "Mutual NDA",
    description: "Protect unreleased beats and session files before you send them.",
    showDeal: false,
    defaultTerms: `1. CONFIDENTIAL INFORMATION. Each party ("Receiving Party") may receive confidential material from the other party ("Disclosing Party"), including unreleased recordings, beat files, session stems, business terms, and contact information ("Confidential Information").

2. OBLIGATIONS. The Receiving Party shall (a) hold all Confidential Information in strict confidence, (b) not disclose it to any third party without prior written consent, and (c) use it solely to evaluate and perform the potential collaboration between the parties.

3. EXCLUSIONS. These obligations do not apply to information that is or becomes public through no fault of the Receiving Party, was lawfully known prior to disclosure, or is independently developed without use of Confidential Information.

4. TERM. This agreement applies to all Confidential Information exchanged between the parties and remains in effect for three (3) years from the date of signing.

5. NO OBLIGATION. Neither party is obligated to enter any further agreement by signing this document.`,
  },
];

export const getTemplate = (id) => CONTRACT_TEMPLATES.find((t) => t.id === id) || CONTRACT_TEMPLATES[0];