// ─────────────────────────────────────────────────────────────────────────────
// Expanded nationwide venue database for Gig Finder.
// Covers all 50 states — smaller markets and secondary cities that the core
// list misses. Same record shape as the in-page VENUE_DB in GigFinder.jsx.
// ─────────────────────────────────────────────────────────────────────────────
export const EXPANDED_VENUE_DB = [
  // ── Alabama ──
  { name: "Mars Music Hall", city: "Huntsville, AL", capacity: 950, genres: ["Rock", "Indie", "Country", "Hip Hop"], pay: "$300-$1500", booking_email: "booking@marsmusichall.com", type: "Concert Hall", website: "https://www.marsmusichall.com", notes: "Huntsville's flagship mid-size room inside the Mars music campus." },
  { name: "Soul Kitchen Music Hall", city: "Mobile, AL", capacity: 350, genres: ["Rock", "Indie", "Blues", "Jam"], pay: "$150-$600", booking_email: "booking@soulkitchenmobile.com", type: "Club", website: "https://www.soulkitchenmobile.com", notes: "Mobile's go-to independent club. Gulf Coast touring stop." },
  { name: "Green Bar", city: "Tuscaloosa, AL", capacity: 200, genres: ["Indie", "Rock", "Hip Hop", "R&B"], pay: "$100-$350", booking_email: "booking@greenbartuscaloosa.com", type: "Bar/Venue", website: "https://www.greenbartuscaloosa.com", notes: "University of Alabama college market. Great for emerging touring acts." },
  { name: "The Druid City Music Hall", city: "Tuscaloosa, AL", capacity: 600, genres: ["Rock", "Indie", "Country", "Hip Hop"], pay: "$200-$800", booking_email: "booking@druidcitymusichall.com", type: "Concert Hall", website: "https://www.druidcitymusichall.com", notes: "Tuscaloosa mid-size room. Strong regional draw required." },

  // ── Alaska ──
  { name: "The Blue Loon", city: "Fairbanks, AK", capacity: 400, genres: ["Rock", "Indie", "Folk", "Country"], pay: "$150-$500", booking_email: "booking@blueloon.com", type: "Club", website: "https://www.blueloon.com", notes: "Fairbanks' main live music room. Interior Alaska touring stop." },

  // ── Arizona ──
  { name: "The Orpheum Theater", city: "Flagstaff, AZ", capacity: 700, genres: ["Rock", "Indie", "Folk", "Country"], pay: "$250-$1000", booking_email: "booking@orpheumflagstaff.com", type: "Concert Hall", website: "https://www.orpheumflagstaff.com", notes: "Historic Flagstaff theater. Route 66 market between Phoenix and Albuquerque." },
  { name: "Yucca Tap Room", city: "Tempe, AZ", capacity: 250, genres: ["Rock", "Indie", "Punk", "Metal"], pay: "$75-$350", booking_email: "booking@yuccataproom.com", type: "Bar/Venue", website: "https://www.yuccataproom.com", notes: "Tempe dive institution. ASU college market, all-ages friendly." },
  { name: "Marquee Theatre", city: "Tempe, AZ", capacity: 2500, genres: ["Rock", "Indie", "Pop", "Hip Hop", "EDM"], pay: "$800+", booking_email: "booking@marqueetempe.com", type: "Concert Hall", website: "https://www.marqueetempe.com", notes: "Large Tempe amphitheater-style room. Requires established regional draw." },
  { name: "The Nile Theater", city: "Mesa, AZ", capacity: 700, genres: ["Rock", "Metal", "Punk", "Hip Hop"], pay: "$200-$800", booking_email: "booking@niletheater.com", type: "Concert Hall", website: "https://www.niletheater.com", notes: "Historic Mesa theater. All-ages shows, strong underground scene." },

  // ── Arkansas ──
  { name: "The Rev Room", city: "Little Rock, AR", capacity: 400, genres: ["Rock", "Indie", "Hip Hop", "Country"], pay: "$150-$600", booking_email: "booking@therevroom.com", type: "Club", website: "https://www.therevroom.com", notes: "Little Rock's premier live music room in the River Market district." },
  { name: "Stickyz Rock 'n' Roll Chicken Shack", city: "Little Rock, AR", capacity: 275, genres: ["Rock", "Indie", "Blues", "Hip Hop"], pay: "$100-$400", booking_email: "booking@stickyz.com", type: "Bar/Venue", website: "https://www.stickyz.com", notes: "Beloved Little Rock club. National touring acts play this small room." },
  { name: "George's Majestic Lounge", city: "Fayetteville, AR", capacity: 375, genres: ["Rock", "Indie", "Jam", "Country"], pay: "$150-$600", booking_email: "booking@georgesmajestic.com", type: "Bar/Venue", website: "https://www.georgesmajestic.com", notes: "University of Arkansas market. Oldest live music venue in the state." },

  // ── California (expanded) ──
  { name: "Alex's Bar", city: "Long Beach, CA", capacity: 200, genres: ["Rock", "Indie", "Punk", "Rockabilly"], pay: "$100-$350", booking_email: "booking@alexsbar.com", type: "Bar/Venue", website: "https://www.alexsbar.com", notes: "Long Beach punk and indie institution. Very supportive of touring acts." },
  { name: "The Observatory", city: "Santa Ana, CA", capacity: 550, genres: ["Indie", "Rock", "Hip Hop", "EDM"], pay: "$250-$1200", booking_email: "booking@theobservatoryoc.com", type: "Concert Hall", website: "https://www.theobservatoryoc.com", notes: "Orange County's flagship independent venue. Constellation Room downstairs." },
  { name: "The Constellation Room", city: "Santa Ana, CA", capacity: 300, genres: ["Indie", "Rock", "Hip Hop", "Pop"], pay: "$150-$600", booking_email: "booking@theobservatoryoc.com", type: "Club", website: "https://www.theobservatoryoc.com", notes: "Intimate upstairs room at The Observatory. Great emerging-act room in OC." },
  { name: "Ventura Theater", city: "Ventura, CA", capacity: 1200, genres: ["Rock", "Indie", "Pop", "Reggae", "Hip Hop"], pay: "$350-$2000", booking_email: "booking@venturatheater.com", type: "Concert Hall", website: "https://www.venturatheater.com", notes: "Historic beach-town theater. Key stop on the LA-to-Santa Barbara run." },
  { name: "Sovereign Bar & Kitchen", city: "Goleta, CA", capacity: 250, genres: ["Indie", "Rock", "Pop", "Folk"], pay: "$100-$400", booking_email: "booking@sovereigngoleta.com", type: "Bar/Venue", website: "https://www.sovereigngoleta.com", notes: "UC Santa Barbara college market. Small room with loyal student crowd." },
  { name: "The Catalyst", city: "Santa Cruz, CA", capacity: 800, genres: ["Rock", "Indie", "Jam", "Reggae", "Hip Hop"], pay: "$250-$1200", booking_email: "booking@catalystclub.com", type: "Concert Hall", website: "https://www.catalystclub.com", notes: "Santa Cruz legend. Multi-room venue, surf-town crowd, strong touring calendar." },
  { name: "Moe's Alley", city: "Santa Cruz, CA", capacity: 300, genres: ["Blues", "Reggae", "Rock", "Jam", "Folk"], pay: "$150-$500", booking_email: "booking@moesalley.com", type: "Club", website: "https://www.moesalley.com", notes: "Intimate Santa Cruz club. Roots, blues, and reggae forward." },
  { name: "SLO Brew Rock", city: "San Luis Obispo, CA", capacity: 500, genres: ["Rock", "Indie", "Pop", "Hip Hop"], pay: "$200-$800", booking_email: "booking@slobrew.com", type: "Bar/Venue", website: "https://www.slobrew.com", notes: "Cal Poly college market. Central Coast touring staple." },
  { name: "Bakersfield Fox Theater", city: "Bakersfield, CA", capacity: 1500, genres: ["Country", "Rock", "Latin", "Pop"], pay: "$400-$2000", booking_email: "booking@foxbakersfield.com", type: "Concert Hall", website: "https://www.foxbakersfield.com", notes: "Historic Bakersfield theater. Deep country and Bakersfield-sound heritage." },
  { name: "The State Theatre", city: "Modesto, CA", capacity: 1100, genres: ["Rock", "Indie", "Country", "Pop"], pay: "$300-$1500", booking_email: "booking@thestatemodesto.com", type: "Concert Hall", website: "https://www.thestatemodesto.com", notes: "Restored 1934 theater. Central Valley market between the Bay and Fresno." },
  { name: "Riverside Municipal Auditorium", city: "Riverside, CA", capacity: 1600, genres: ["Rock", "Indie", "Hip Hop", "Pop", "EDM"], pay: "$400-$2000", booking_email: "booking@riversidema.com", type: "Concert Hall", website: "https://www.riversideca.gov", notes: "Inland Empire mid-size room. Historic Spanish Revival auditorium." },
  { name: "The Phoenix Theater", city: "Petaluma, CA", capacity: 250, genres: ["Punk", "Rock", "Indie", "Metal"], pay: "$75-$300", booking_email: "booking@phoenixtheater.com", type: "Club", website: "https://www.phoenixtheater.com", notes: "Legendary all-ages Sonoma County punk venue. Very DIY-friendly." },
  { name: "Mystic Theatre", city: "Petaluma, CA", capacity: 500, genres: ["Rock", "Indie", "Country", "Pop"], pay: "$200-$800", booking_email: "booking@mystictheatre.com", type: "Concert Hall", website: "https://www.mystictheatre.com", notes: "Downtown Petaluma room. North Bay touring stop." },
  { name: "The Luther", city: "Santa Rosa, CA", capacity: 300, genres: ["Indie", "Rock", "Folk", "Country"], pay: "$150-$500", booking_email: "booking@theluthersonoma.com", type: "Club", website: "https://www.theluthersonoma.com", notes: "Sonoma County listening room. Strong singer-songwriter bookings." },
  { name: "The Senator Theatre", city: "Chico, CA", capacity: 900, genres: ["Rock", "Indie", "Pop", "Hip Hop"], pay: "$250-$1000", booking_email: "booking@senatorchico.com", type: "Concert Hall", website: "https://www.senatorchico.com", notes: "College town market. Key stop between Sacramento and Oregon." },
  { name: "Humboldt Brews", city: "Arcata, CA", capacity: 250, genres: ["Rock", "Reggae", "Jam", "Indie"], pay: "$100-$400", booking_email: "booking@humboldtbrews.com", type: "Bar/Venue", website: "https://www.humboldtbrews.com", notes: "Humboldt County club. Remote NorCal market with dedicated music crowd." },
  { name: "Blue Note Napa", city: "Napa, CA", capacity: 250, genres: ["Jazz", "R&B", "Pop", "Soul"], pay: "$150-$600", booking_email: "booking@bluenotenapa.com", type: "Club", website: "https://www.bluenotenapa.com", notes: "Wine country jazz club. Upsulate intimate room for polished acts." },
  { name: "South Shore Room", city: "Stateline, NV", capacity: 1900, genres: ["Rock", "Pop", "Hip Hop", "EDM"], pay: "$500+", booking_email: "booking@southshoreroom.com", type: "Concert Hall", website: "https://www.southshoreroom.com", notes: "Lake Tahoe showroom. Destination market for regional touring acts." },

  // ── Colorado (expanded) ──
  { name: "The Fox Theatre", city: "Boulder, CO", capacity: 500, genres: ["Rock", "Indie", "Jam", "Pop", "Hip Hop"], pay: "$250-$1000", booking_email: "booking@foxtheatre.com", type: "Concert Hall", website: "https://www.foxtheatre.com", notes: "Boulder institution. CU college market, legendary room on The Hill." },
  { name: "Boulder Theater", city: "Boulder, CO", capacity: 850, genres: ["Indie", "Folk", "Country", "Pop"], pay: "$300-$1500", booking_email: "booking@bouldertheater.com", type: "Concert Hall", website: "https://www.bouldertheater.com", notes: "Historic art deco theater downtown. Mix of seated and standing shows." },
  { name: "eTown Hall", city: "Boulder, CO", capacity: 200, genres: ["Folk", "Singer-Songwriter", "Indie", "Country"], pay: "$150-$500", booking_email: "booking@etown.org", type: "Arts Venue", website: "https://www.etown.org", notes: "Solar-powered listening room and radio taping space. Great for acoustic acts." },
  { name: "Aggie Theatre", city: "Fort Collins, CO", capacity: 500, genres: ["Rock", "Indie", "Hip Hop", "EDM"], pay: "$200-$900", booking_email: "booking@aggietheatre.com", type: "Concert Hall", website: "https://www.aggietheatre.com", notes: "Old Town Fort Collins staple. CSU college market." },
  { name: "Hodi's Half Note", city: "Fort Collins, CO", capacity: 300, genres: ["Rock", "Jam", "Indie", "Funk"], pay: "$100-$400", booking_email: "booking@hodishalfnote.com", type: "Club", website: "https://www.hodishalfnote.com", notes: "Funk and jam-friendly club. Smaller Fort Collins room for emerging acts." },
  { name: "Black Sheep", city: "Colorado Springs, CO", capacity: 400, genres: ["Rock", "Metal", "Indie", "Punk"], pay: "$150-$600", booking_email: "booking@blacksheephq.com", type: "Club", website: "https://www.blacksheephq.com", notes: "Colorado Springs rock club. Heavy and alternative bookings." },
  { name: "Stargazers Theatre", city: "Colorado Springs, CO", capacity: 550, genres: ["Indie", "Folk", "Country", "Rock"], pay: "$200-$800", booking_email: "booking@stargazerstheatre.com", type: "Concert Hall", website: "https://www.stargazerstheatre.com", notes: "Dome-shaped listening venue. Great acoustics for mid-size acts." },
  { name: "Mesa Theater", city: "Grand Junction, CO", capacity: 600, genres: ["Rock", "Indie", "Country", "Hip Hop"], pay: "$200-$800", booking_email: "booking@mesatheatergj.com", type: "Concert Hall", website: "https://www.mesatheatergj.com", notes: "Western Colorado's main club. Only mid-size room between Denver and Salt Lake." },
  { name: "three20 South", city: "Breckenridge, CO", capacity: 250, genres: ["Rock", "Indie", "Jam", "Funk"], pay: "$150-$500", booking_email: "booking@three20south.com", type: "Club", website: "https://www.three20south.com", notes: "Mountain town club. Ski-season crowds make winter bookings lucrative." },

  // ── Connecticut (expanded) ──
  { name: "Cafe Nine", city: "New Haven, CT", capacity: 120, genres: ["Rock", "Blues", "Indie", "Jazz"], pay: "$75-$300", booking_email: "booking@cafenine.com", type: "Bar/Venue", website: "https://www.cafenine.com", notes: "New Haven institution. Best entry-level room in the city." },
  { name: "The Ballroom at The Outer Space", city: "Hamden, CT", capacity: 200, genres: ["Indie", "Rock", "Punk", "Metal"], pay: "$100-$350", booking_email: "booking@theouterspace.net", type: "Club", website: "https://www.theouterspace.net", notes: "Sister to the Space. All-ages shows, very DIY-friendly." },
  { name: "Heirloom Arts Center", city: "Danbury, CT", capacity: 500, genres: ["Rock", "Indie", "Metal", "Hip Hop"], pay: "$200-$700", booking_email: "booking@heirloomartscenter.com", type: "Arts Venue", website: "https://www.heirloomartscenter.com", notes: "Restored theater. Western CT market between NYC and Hartford." },
  { name: "The Klein Memorial Auditorium", city: "Bridgeport, CT", capacity: 1450, genres: ["Rock", "Pop", "R&B", "Indie"], pay: "$400-$2000", booking_email: "booking@theklein.org", type: "Concert Hall", website: "https://www.theklein.org", notes: "Historic Bridgeport theater. Mid-level touring acts." },
  { name: "Garde Arts Center", city: "New London, CT", capacity: 1400, genres: ["Indie", "Folk", "Pop", "Rock"], pay: "$400-$1500", booking_email: "booking@gardearts.org", type: "Concert Hall", website: "https://www.gardearts.org", notes: "Restored 1926 movie palace. Southeastern CT touring room." },

  // ── Delaware ──
  { name: "The Queen", city: "Wilmington, DE", capacity: 600, genres: ["Rock", "Indie", "Hip Hop", "Pop", "R&B"], pay: "$250-$1000", booking_email: "booking@thequeenwilmington.com", type: "Concert Hall", website: "https://www.thequeenwilmington.com", notes: "Restored hotel-turned-venue on Market Street. Delaware's flagship room." },
  { name: "The Grand Opera House", city: "Wilmington, DE", capacity: 1200, genres: ["Folk", "Jazz", "Indie", "Classical"], pay: "$400-$1500", booking_email: "booking@thegrandwilmington.org", type: "Concert Hall", website: "https://www.thegrandwilmington.org", notes: "Historic 1871 opera house. Listening-room shows and seated acts." },
  { name: "Rusty Rudder", city: "Dewey Beach, DE", capacity: 500, genres: ["Rock", "Pop", "Jam", "Country"], pay: "$200-$800", booking_email: "booking@rustyrudder.com", type: "Bar/Venue", website: "https://www.rustyrudder.com", notes: "Beach town bar with big summer crowds. Seasonal bookings May-September." },

  // ── Florida (expanded) ──
  { name: "Jack Rabbit's", city: "Jacksonville, FL", capacity: 400, genres: ["Rock", "Indie", "Punk", "Metal"], pay: "$150-$600", booking_email: "booking@jackrabbitsjacksonville.com", type: "Club", website: "https://www.jackrabbitsjacksonville.com", notes: "Jacksonville's premier small club. All-ages shows." },
  { name: "Underbelly", city: "Jacksonville, FL", capacity: 150, genres: ["Hip Hop", "Indie", "EDM", "R&B"], pay: "$75-$300", booking_email: "booking@underbellyjax.com", type: "Club", website: "https://www.underbellyjax.com", notes: "Downtown JX venue with hip hop and alternative focus." },
  { name: "High Dive", city: "Gainesville, FL", capacity: 400, genres: ["Indie", "Rock", "Hip Hop", "Punk"], pay: "$150-$600", booking_email: "booking@highdivegainesville.com", type: "Club", website: "https://www.highdivegainesville.com", notes: "UF college town. Every touring act between Orlando and Tallahassee plays here." },
  { name: "The Wilbury", city: "Tallahassee, FL", capacity: 200, genres: ["Indie", "Rock", "Hip Hop", "Punk"], pay: "$75-$300", booking_email: "booking@thewilbury.com", type: "Club", website: "https://www.thewilbury.com", notes: "Tallahassee DIY room. FSU market, great for up-and-coming acts." },
  { name: "Vinyl Music Hall", city: "Pensacola, FL", capacity: 400, genres: ["Rock", "Indie", "Metal", "Hip Hop"], pay: "$150-$600", booking_email: "booking@vinylmusichall.com", type: "Club", website: "https://www.vinylmusichall.com", notes: "Pensacola's main independent club. Gulf Coast touring stop." },
  { name: "Churchill's Pub", city: "Miami, FL", capacity: 300, genres: ["Punk", "Rock", "Metal", "Indie"], pay: "$75-$300", booking_email: "booking@churchillspub.com", type: "Bar/Venue", website: "https://www.churchillspub.com", notes: "Legendary Little Haiti punk institution. Raw, authentic, all-ages." },
  { name: "Ball & Chain", city: "Miami, FL", capacity: 200, genres: ["Latin", "Jazz", "Salsa", "R&B"], pay: "$100-$500", booking_email: "booking@ballandchainmiami.com", type: "Club", website: "https://www.ballandchainmiami.com", notes: "Historic Calle Ocho club. Latin jazz and salsa bookings nightly." },
  { name: "The Blue Rooster", city: "Sarasota, FL", capacity: 200, genres: ["Blues", "Rock", "Indie", "Folk"], pay: "$100-$400", booking_email: "booking@blueroostersarasota.com", type: "Bar/Venue", website: "https://www.blueroostersarasota.com", notes: "Sarasota blues room. Older crowd, strong listening-room vibe." },
  { name: "Bank & Blues Club", city: "Daytona Beach, FL", capacity: 200, genres: ["Blues", "Rock", "Jam", "Country"], pay: "$100-$400", booking_email: "booking@bankandblues.com", type: "Bar/Venue", website: "https://www.bankandblues.com", notes: "Beachside blues club. Bike Week and spring break crowds spike attendance." },
  { name: "House of Rock", city: "Corpus Christi, TX", capacity: 500, genres: ["Rock", "Metal", "Indie", "Country"], pay: "$150-$700", booking_email: "booking@houseofrockcc.com", type: "Club", website: "https://www.houseofrockcc.com", notes: "Corpus Christi's main rock room. Gulf Coast Texas touring stop." },

  // ── Georgia (expanded) ──
  { name: "The Cox Capitol Theatre", city: "Macon, GA", capacity: 600, genres: ["Rock", "Indie", "Country", "Soul"], pay: "$200-$900", booking_email: "booking@coxcapitoltheatre.com", type: "Concert Hall", website: "https://www.coxcapitoltheatre.com", notes: "Restored Macon theater. Deep soul and Southern rock heritage market." },
  { name: "The Miller Theater", city: "Augusta, GA", capacity: 1100, genres: ["Rock", "Pop", "Indie", "Country"], pay: "$300-$1500", booking_email: "booking@themilleraugusta.com", type: "Concert Hall", website: "https://www.themilleraugusta.com", notes: "Restored 1940 art moderne theater. Central Georgia touring room." },
  { name: "The Loft", city: "Columbus, GA", capacity: 300, genres: ["Rock", "Indie", "Hip Hop", "Metal"], pay: "$100-$500", booking_email: "booking@theloftcolumbus.com", type: "Club", website: "https://www.theloftcolumbus.com", notes: "Columbus' main independent club. Fort Benning market." },
  { name: "Caledonia Lounge", city: "Athens, GA", capacity: 150, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$50-$250", booking_email: "booking@caledonialounge.com", type: "Bar/Venue", website: "https://www.caledonialounge.com", notes: "Tiny Athens room where countless indie legends played early shows." },

  // ── Hawaii ──
  { name: "MaiTais Bar", city: "Honolulu, HI", capacity: 300, genres: ["Reggae", "Hip Hop", "R&B", "Pop"], pay: "$150-$600", booking_email: "booking@maitaisbar.com", type: "Bar/Venue", website: "https://www.maitaisbar.com", notes: "Waikiki beachfront stage. Reggae and island-music crowds nightly." },

  // ── Idaho (expanded) ──
  { name: "John's Alley Tavern", city: "Moscow, ID", capacity: 150, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$50-$250", booking_email: "booking@johnsalley.com", type: "Bar/Venue", website: "https://www.johnsalley.com", notes: "University of Idaho college town. Legendary Northwest DIY stop." },
  { name: "The Vault", city: "Coeur d'Alene, ID", capacity: 250, genres: ["Rock", "Indie", "Blues", "Country"], pay: "$100-$400", booking_email: "booking@thevaultcda.com", type: "Club", website: "https://www.thevaultcda.com", notes: "Northern Idaho's main club. Spokane-adjacent market." },
  { name: "The Celt Pub", city: "Idaho Falls, ID", capacity: 150, genres: ["Rock", "Folk", "Celtic", "Indie"], pay: "$50-$200", booking_email: "booking@theceltidahofalls.com", type: "Bar/Venue", website: "https://www.theceltidahofalls.com", notes: "Eastern Idaho stop between Salt Lake and Bozeman runs." },

  // ── Illinois (expanded) ──
  { name: "The Canopy Club", city: "Urbana, IL", capacity: 500, genres: ["Hip Hop", "Indie", "EDM", "Rock"], pay: "$200-$800", booking_email: "booking@canopyclub.com", type: "Club", website: "https://www.canopyclub.com", notes: "UIUC college market. Every Midwest tour routes through Champaign." },
  { name: "SPACE", city: "Evanston, IL", capacity: 240, genres: ["Folk", "Indie", "Singer-Songwriter", "Jazz"], pay: "$150-$600", booking_email: "booking@evanstonspace.com", type: "Arts Venue", website: "https://www.evanstonspace.com", notes: "Pristine listening room just north of Chicago. Radio-friendly acts do well." },
  { name: "Apollo Theatre", city: "Peoria, IL", capacity: 1400, genres: ["Rock", "Pop", "Country", "Hip Hop"], pay: "$350-$1800", booking_email: "booking@apollopeoria.com", type: "Concert Hall", website: "https://www.apollopeoria.com", notes: "Restored historic theater. Central Illinois touring stop." },
  { name: "The Pink Room", city: "Peoria, IL", capacity: 200, genres: ["Metal", "Rock", "Punk", "Indie"], pay: "$75-$300", booking_email: "booking@thepinkroompeoria.com", type: "Club", website: "https://www.thepinkroompeoria.com", notes: "Peoria's underground room. Heavy music focus." },

  // ── Indiana (expanded) ──
  { name: "Piere's Entertainment Center", city: "Fort Wayne, IN", capacity: 1400, genres: ["Rock", "Metal", "Hip Hop", "EDM"], pay: "$300-$1500", booking_email: "booking@pieres.com", type: "Concert Hall", website: "https://www.pieres.com", notes: "Fort Wayne's main club. Heavy touring calendar, regional draw required." },
  { name: "Be Here Now", city: "Muncie, IN", capacity: 200, genres: ["Indie", "Rock", "Punk", "Hip Hop"], pay: "$75-$300", booking_email: "booking@beherenowmuncie.com", type: "Bar/Venue", website: "https://www.beherenowmuncie.com", notes: "Ball State college market. DIY-friendly all-ages room." },

  // ── Iowa (expanded) ──
  { name: "CSPS Hall", city: "Cedar Rapids, IA", capacity: 250, genres: ["Folk", "Indie", "World", "Jazz"], pay: "$150-$500", booking_email: "booking@csps.org", type: "Arts Venue", website: "https://www.csps.org", notes: "Historic Czech cultural hall turned listening room. Eastern Iowa market." },
  { name: "The Mill", city: "Iowa City, IA", capacity: 200, genres: ["Folk", "Singer-Songwriter", "Indie", "Blues"], pay: "$100-$400", booking_email: "booking@icmill.com", type: "Bar/Venue", website: "https://www.icmill.com", notes: "Iowa City listening-room institution. Writers' round vibe." },

  // ── Kansas (expanded) ──
  { name: "The Cotillion", city: "Wichita, KS", capacity: 2000, genres: ["Rock", "Country", "Hip Hop", "Metal"], pay: "$500+", booking_email: "booking@thecotillion.com", type: "Concert Hall", website: "https://www.thecotillion.com", notes: "Wichita's main mid-size room. Regional draw needed." },
  { name: "Kirby's Beer Store", city: "Wichita, KS", capacity: 100, genres: ["Indie", "Punk", "Rock", "Folk"], pay: "$50-$200", booking_email: "booking@kirbysbeerstore.com", type: "Bar/Venue", website: "https://www.kirbysbeerstore.com", notes: "Tiny legendary Wichita dive. Where Midwest indie acts cut their teeth." },
  { name: "Replay Lounge", city: "Lawrence, KS", capacity: 150, genres: ["Indie", "Punk", "Rock", "Metal"], pay: "$50-$250", booking_email: "booking@replaylounge.com", type: "Bar/Venue", website: "https://www.replaylounge.com", notes: "Lawrence dive institution. Pinball, cheap beer, great shows." },
  { name: "Uncle Bo's", city: "Topeka, KS", capacity: 200, genres: ["Blues", "Rock", "Jam", "Country"], pay: "$75-$350", booking_email: "booking@unclebos.com", type: "Bar/Venue", website: "https://www.unclebos.com", notes: "Topeka's blues and roots room. Small but dedicated crowd." },

  // ── Kentucky (expanded) ──
  { name: "Manchester Music Hall", city: "Lexington, KY", capacity: 600, genres: ["Rock", "Indie", "Country", "Jam"], pay: "$250-$1000", booking_email: "booking@manchestermusichall.com", type: "Concert Hall", website: "https://www.manchestermusichall.com", notes: "Lexington's main independent room. UK college market." },
  { name: "The Green Lantern", city: "Lexington, KY", capacity: 200, genres: ["Indie", "Rock", "Punk", "Metal"], pay: "$75-$300", booking_email: "booking@greenlanternlex.com", type: "Bar/Venue", website: "https://www.greenlanternlex.com", notes: "Dive bar with a serious music habit. Entry-level Lexington bookings." },
  { name: "The Burl", city: "Lexington, KY", capacity: 150, genres: ["Folk", "Indie", "Americana", "Country"], pay: "$100-$400", booking_email: "booking@theburl.com", type: "Bar/Venue", website: "https://www.theburl.com", notes: "Rail-yard listening room. Americana-forward with excellent curation." },
  { name: "The Madison Theater", city: "Covington, KY", capacity: 600, genres: ["Rock", "Indie", "Hip Hop", "Pop"], pay: "$250-$1000", booking_email: "booking@madisontheater.com", type: "Concert Hall", website: "https://www.madisontheater.com", notes: "Northern Kentucky room steps from Cincinnati. Art deco ballroom." },
  { name: "Tidball's", city: "Bowling Green, KY", capacity: 200, genres: ["Rock", "Metal", "Punk", "Indie"], pay: "$75-$300", booking_email: "booking@tidballs.com", type: "Bar/Venue", website: "https://www.tidballs.com", notes: "WKU college market. Classic Southern college-town rock bar." },

  // ── Louisiana (expanded) ──
  { name: "The Varsity Theatre", city: "Baton Rouge, LA", capacity: 1000, genres: ["Rock", "Indie", "Hip Hop", "EDM"], pay: "$300-$1500", booking_email: "booking@varsitytheatre.com", type: "Concert Hall", website: "https://www.varsitytheatre.com", notes: "LSU market. Baton Rouge's main mid-size touring room." },
  { name: "Texas Club", city: "Baton Rouge, LA", capacity: 500, genres: ["Country", "Rock", "Jam", "Blues"], pay: "$200-$800", booking_email: "booking@texasclub.com", type: "Club", website: "https://www.texasclub.com", notes: "Legendary Baton Rouge roadhouse. Country and Southern rock crowd." },
  { name: "The Blue Moon Saloon", city: "Lafayette, LA", capacity: 200, genres: ["Cajun", "Country", "Americana", "Rock"], pay: "$100-$400", booking_email: "booking@bluemoonpresents.com", type: "Bar/Venue", website: "https://www.bluemoonpresents.com", notes: "Backporch stage behind a dive bar. The heart of Cajun country touring." },
  { name: "Gasa Gasa", city: "New Orleans, LA", capacity: 100, genres: ["Indie", "Jazz", "Experimental", "R&B"], pay: "$75-$300", booking_email: "booking@gasagasa.com", type: "Club", website: "https://www.gasagasa.com", notes: "Freret Street listening room. Eclectic, genre-forward bookings." },
  { name: "Siberia", city: "New Orleans, LA", capacity: 250, genres: ["Metal", "Punk", "Rock", "Hip Hop"], pay: "$100-$400", booking_email: "booking@siberianola.com", type: "Club", website: "https://www.siberianola.com", notes: "St. Claude corridor club for heavier and weirder touring acts." },

  // ── Maine (expanded) ──
  { name: "One Longfellow Square", city: "Portland, ME", capacity: 220, genres: ["Folk", "Singer-Songwriter", "Indie", "Jazz"], pay: "$150-$600", booking_email: "booking@onelongfellowsquare.com", type: "Arts Venue", website: "https://www.onelongfellowsquare.com", notes: "Portland's premier listening room. Songwriter circuit staple." },
  { name: "Bull Feeney's", city: "Portland, ME", capacity: 150, genres: ["Folk", "Irish", "Rock", "Americana"], pay: "$75-$300", booking_email: "booking@bullfeeneys.com", type: "Bar/Venue", website: "https://www.bullfeeneys.com", notes: "Irish pub with live music nightly. Entry-level Portland room." },

  // ── Maryland (expanded) ──
  { name: "Bethesda Blues & Jazz Supper Club", city: "Bethesda, MD", capacity: 400, genres: ["Jazz", "Blues", "R&B", "Soul"], pay: "$200-$800", booking_email: "booking@bethesdablues.com", type: "Club", website: "https://www.bethesdablues.com", notes: "Dinner-and-show format. Polished acts with strong live presentation." },
  { name: "Seacrets", city: "Ocean City, MD", capacity: 800, genres: ["Reggae", "Rock", "Pop", "Country"], pay: "$250-$1000", booking_email: "booking@seacrets.com", type: "Bar/Venue", website: "https://www.seacrets.com", notes: "Massive beachfront complex. Summer season bookings draw huge crowds." },

  // ── Massachusetts (expanded) ──
  { name: "The Palladium", city: "Worcester, MA", capacity: 2200, genres: ["Metal", "Rock", "Punk", "EDM"], pay: "$500+", booking_email: "booking@thepalladium.net", type: "Concert Hall", website: "https://www.thepalladium.net", notes: "New England's metal mecca. Hardcore and heavy touring required." },
  { name: "The Lucky Dog Music Hall", city: "Worcester, MA", capacity: 120, genres: ["Rock", "Punk", "Indie", "Metal"], pay: "$50-$250", booking_email: "booking@luckydognightclub.com", type: "Bar/Venue", website: "https://www.luckydognightclub.com", notes: "Worcester dive institution. Every Boston band plays here eventually." },
  { name: "Great Scott", city: "Allston, MA", capacity: 220, genres: ["Indie", "Rock", "Punk", "Hip Hop"], pay: "$100-$400", booking_email: "booking@greatscottboston.com", type: "Bar/Venue", website: "https://www.greatscottboston.com", notes: "Allston rock bar. The room where national indie acts play small on the way up." },
  { name: "Theodores' Blues Club", city: "Springfield, MA", capacity: 200, genres: ["Blues", "Rock", "Jam", "Funk"], pay: "$100-$400", booking_email: "booking@theodoresblues.com", type: "Bar/Venue", website: "https://www.theodoresblues.com", notes: "Springfield blues bar. Western MA touring stop." },

  // ── Michigan (expanded) ──
  { name: "The Machine Shop", city: "Flint, MI", capacity: 600, genres: ["Metal", "Rock", "Punk", "Hardcore"], pay: "$200-$800", booking_email: "booking@theshopflint.com", type: "Concert Hall", website: "https://www.theshopflint.com", notes: "Flint's rock room. National heavy touring acts play here weekly." },
  { name: "Bell's Eccentric Cafe", city: "Kalamazoo, MI", capacity: 300, genres: ["Indie", "Rock", "Folk", "Jam"], pay: "$150-$500", booking_email: "booking@bellsbeer.com", type: "Bar/Venue", website: "https://www.bellsbeer.com", notes: "Brewery venue from Bell's Beer. Great room and college crowd." },
  { name: "The Strutt", city: "Kalamazoo, MI", capacity: 150, genres: ["Jazz", "Funk", "Indie", "Hip Hop"], pay: "$75-$300", booking_email: "booking@thestrutt.com", type: "Bar/Venue", website: "https://www.thestrutt.com", notes: "Kalamazoo cafe with nightly live music. Eclectic and artist-friendly." },
  { name: "The Green Door", city: "Lansing, MI", capacity: 250, genres: ["Indie", "Rock", "Punk", "Metal"], pay: "$100-$350", booking_email: "booking@thegreendoorlansing.com", type: "Club", website: "https://www.thegreendoorlansing.com", notes: "Lansing's indie rock room. MSU market." },
  { name: "The Elbow Room", city: "Ypsilanti, MI", capacity: 150, genres: ["Rock", "Punk", "Indie", "Blues"], pay: "$50-$250", booking_email: "booking@elbowroomypsi.com", type: "Bar/Venue", website: "https://www.elbowroomypsi.com", notes: "Ypsi dive bar. Raw rock and punk shows near Ann Arbor." },
  { name: "Mohawk Place", city: "Buffalo, NY", capacity: 300, genres: ["Indie", "Rock", "Punk", "Metal"], pay: "$150-$500", booking_email: "booking@mohawkplace.com", type: "Bar/Venue", website: "https://www.mohawkplace.com", notes: "Buffalo's best small room. Touring bands between Cleveland and Toronto." },

  // ── Minnesota (expanded) ──
  { name: "Sacred Heart Music Center", city: "Duluth, MN", capacity: 400, genres: ["Folk", "Indie", "Americana", "Classical"], pay: "$200-$700", booking_email: "booking@sacredheartmusic.org", type: "Arts Venue", website: "https://www.sacredheartmusic.org", notes: "Restored cathedral with stunning acoustics. Duluth's listening room." },
  { name: "Tycoon's", city: "Duluth, MN", capacity: 200, genres: ["Rock", "Indie", "Jam", "Blues"], pay: "$100-$400", booking_email: "booking@tycoonsduluth.com", type: "Bar/Venue", website: "https://www.tycoonsduluth.com", notes: "Downtown Duluth club. Arrowhead region touring stop." },

  // ── Mississippi ──
  { name: "Duling Hall", city: "Jackson, MS", capacity: 400, genres: ["Rock", "Indie", "Country", "Blues"], pay: "$150-$600", booking_email: "booking@dulinghall.com", type: "Concert Hall", website: "https://www.dulinghall.com", notes: "Fondren district venue. Jackson's premier small touring room." },
  { name: "Proud Larry's", city: "Oxford, MS", capacity: 250, genres: ["Rock", "Indie", "Jam", "Country"], pay: "$100-$400", booking_email: "booking@proudlarrys.com", type: "Bar/Venue", website: "https://www.proudlarrys.com", notes: "Ole Miss college town. Great Southeastern touring stop." },

  // ── Missouri (expanded) ──
  { name: "The Blue Note", city: "Columbia, MO", capacity: 700, genres: ["Rock", "Indie", "Hip Hop", "Country"], pay: "$250-$1000", booking_email: "booking@thebluenote.com", type: "Concert Hall", website: "https://www.thebluenote.com", notes: "Mizzou college market. Legendary Midwest touring stop since 1980." },
  { name: "Rose Music Hall", city: "Columbia, MO", capacity: 300, genres: ["Rock", "Indie", "Punk", "Metal"], pay: "$150-$500", booking_email: "booking@rosemusichall.com", type: "Club", website: "https://www.rosemusichall.com", notes: "The Blue Note's smaller sister room. Up-and-coming acts." },
  { name: "The Outland Ballroom", city: "Springfield, MO", capacity: 300, genres: ["Rock", "Indie", "Metal", "Punk"], pay: "$100-$500", booking_email: "booking@outlandballroom.com", type: "Club", website: "https://www.outlandballroom.com", notes: "Springfield MO's main club. Route 66 market between St. Louis and Tulsa." },

  // ── Montana (expanded) ──
  { name: "The Pub Station", city: "Billings, MT", capacity: 600, genres: ["Rock", "Country", "Indie", "Metal"], pay: "$200-$800", booking_email: "booking@pubstation.com", type: "Concert Hall", website: "https://www.pubstation.com", notes: "Billings' main venue. The gateway stop for all Montana tours." },
  { name: "The Filling Station", city: "Bozeman, MT", capacity: 400, genres: ["Rock", "Indie", "Jam", "Country"], pay: "$150-$600", booking_email: "booking@fillingstationbozeman.com", type: "Club", website: "https://www.fillingstationbozeman.com", notes: "Bozeman's rock club. MSU college market with a strong music town vibe." },
  { name: "The ELM", city: "Bozeman, MT", capacity: 1100, genres: ["Rock", "Indie", "Pop", "Hip Hop"], pay: "$300-$1500", booking_email: "booking@theelmbozeman.com", type: "Concert Hall", website: "https://www.theelmbozeman.com", notes: "Bozeman's flagship mid-size room opened by the Log Jam Presents team." },

  // ── Nebraska (expanded) ──
  { name: "Duffy's Tavern", city: "Lincoln, NE", capacity: 250, genres: ["Rock", "Indie", "Punk", "Metal"], pay: "$100-$400", booking_email: "booking@duffystavern.com", type: "Bar/Venue", website: "https://www.duffystavern.com", notes: "Lincoln rock institution since 1972. UNL college crowd." },
  { name: "Bodega's Alley", city: "Lincoln, NE", capacity: 150, genres: ["Indie", "Rock", "Hip Hop", "Folk"], pay: "$75-$300", booking_email: "booking@bodogasalloy.com", type: "Bar/Venue", website: "https://www.bodegasalley.com", notes: "Tiny alley club. Where Lincoln's underground scene lives." },

  // ── Nevada (expanded) ──
  { name: "The Saint", city: "Reno, NV", capacity: 250, genres: ["Rock", "Indie", "Punk", "Metal"], pay: "$100-$400", booking_email: "booking@thesaintreno.com", type: "Club", website: "https://www.thesaintreno.com", notes: "Reno's best small room. Touring acts between Sacramento and Salt Lake." },

  // ── New Hampshire (expanded) ──
  { name: "The Press Room", city: "Portsmouth, NH", capacity: 100, genres: ["Jazz", "Blues", "Rock", "Folk"], pay: "$75-$300", booking_email: "booking@pressroomnh.com", type: "Bar/Venue", website: "https://www.pressroomnh.com", notes: "Portsmouth basement bar with nightly live music since 1976." },
  { name: "The Palace Theatre", city: "Manchester, NH", capacity: 800, genres: ["Rock", "Pop", "Indie", "Country"], pay: "$300-$1200", booking_email: "booking@palacetheatre.org", type: "Concert Hall", website: "https://www.palacetheatre.org", notes: "Manchester's historic 1915 theater. Mid-level touring acts." },

  // ── New Jersey ──
  { name: "The Stone Pony", city: "Asbury Park, NJ", capacity: 850, genres: ["Rock", "Indie", "Pop", "Punk"], pay: "$300-$1200", booking_email: "booking@stoneponyonline.com", type: "Concert Hall", website: "https://www.stoneponyonline.com", notes: "Springsteen's home venue. The most iconic rock room on the Jersey Shore." },
  { name: "The Saint", city: "Asbury Park, NJ", capacity: 150, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$75-$300", booking_email: "booking@thesaintnj.com", type: "Bar/Venue", website: "https://www.thesaintnj.com", notes: "Asbury Park's small room. Where Shore bands build their following." },
  { name: "Asbury Lanes", city: "Asbury Park, NJ", capacity: 700, genres: ["Rock", "Punk", "Indie", "Rockabilly"], pay: "$200-$900", booking_email: "booking@asburylanes.com", type: "Club", website: "https://www.asburylanes.com", notes: "Retro bowling alley with a stage in the lanes. Iconic Asbury vibe." },
  { name: "Court Tavern", city: "New Brunswick, NJ", capacity: 200, genres: ["Indie", "Rock", "Punk", "Metal"], pay: "$100-$350", booking_email: "booking@courttavern.com", type: "Bar/Venue", website: "https://www.courttavern.com", notes: "Rutgers college market. Basement shows with serious scene history." },
  { name: "Maxwell's", city: "Hoboken, NJ", capacity: 200, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$100-$400", booking_email: "booking@maxwellsnj.com", type: "Bar/Venue", website: "https://www.maxwellsnj.com", notes: "Legendary Hoboken club. NYC-adjacent with deep indie history." },
  { name: "White Eagle Hall", city: "Jersey City, NJ", capacity: 250, genres: ["Indie", "Rock", "Pop", "Hip Hop"], pay: "$200-$800", booking_email: "booking@whiteeaglehalljc.com", type: "Concert Hall", website: "https://www.whiteeaglehalljc.com", notes: "Restored theater in the Journal Square district. NYC alternative." },
  { name: "Anchor Rock Club", city: "Atlantic City, NJ", capacity: 300, genres: ["Rock", "Indie", "Punk", "Hip Hop"], pay: "$150-$600", booking_email: "booking@anchorrockclub.com", type: "Club", website: "https://www.anchorrockclub.com", notes: "Atlantic City's one true independent music venue. Off-boardwalk." },
  { name: "Just Jake's", city: "Montclair, NJ", capacity: 200, genres: ["Indie", "Rock", "Pop", "Jam"], pay: "$100-$400", booking_email: "booking@justjakeslive.com", type: "Bar/Venue", website: "https://www.justjakeslive.com", notes: "Montclair's main live room. Artsy Essex County crowd." },

  // ── New Mexico (expanded) ──
  { name: "The Lensic Performing Arts Center", city: "Santa Fe, NM", capacity: 800, genres: ["Folk", "Indie", "World", "Americana"], pay: "$300-$1200", booking_email: "booking@lensic.org", type: "Arts Venue", website: "https://www.lensic.org", notes: "Santa Fe's 1931 landmark theater. Listening-room audiences." },
  { name: "Cowgirl", city: "Santa Fe, NM", capacity: 300, genres: ["Country", "Rock", "Americana", "Blues"], pay: "$150-$600", booking_email: "booking@cowgirlsantafe.com", type: "Bar/Venue", website: "https://www.cowgirlsantafe.com", notes: "Santa Fe roadhouse with BBQ and nightly live music." },
  { name: "Rio Grande Theatre", city: "Las Cruces, NM", capacity: 400, genres: ["Rock", "Indie", "Country", "Latin"], pay: "$150-$600", booking_email: "booking@riograndetheatre.org", type: "Concert Hall", website: "https://www.riograndetheatre.org", notes: "Southern New Mexico market. El Paso-adjacent touring stop." },

  // ── New York (expanded upstate + metro) ──
  { name: "The Bug Jar", city: "Rochester, NY", capacity: 300, genres: ["Indie", "Rock", "Punk", "Metal"], pay: "$150-$500", booking_email: "booking@thebugjar.com", type: "Club", website: "https://www.thebugjar.com", notes: "Rochester's premier small venue. Every indie tour stops here." },
  { name: "Westcott Theater", city: "Syracuse, NY", capacity: 700, genres: ["Rock", "Indie", "Hip Hop", "EDM"], pay: "$250-$1000", booking_email: "booking@westcotttheater.com", type: "Concert Hall", website: "https://www.westcotttheater.com", notes: "Syracuse's main independent room. SU college market." },
  { name: "The Lost Horizon", city: "Syracuse, NY", capacity: 300, genres: ["Metal", "Rock", "Punk", "Hardcore"], pay: "$100-$400", booking_email: "booking@losthorizonlive.com", type: "Club", website: "https://www.losthorizonlive.com", notes: "Syracuse metal institution. Heavy touring acts." },
  { name: "The Hollow Bar + Kitchen", city: "Albany, NY", capacity: 250, genres: ["Rock", "Indie", "Jam", "Blues"], pay: "$100-$400", booking_email: "booking@thehollowalbany.com", type: "Bar/Venue", website: "https://www.thehollowalbany.com", notes: "Albany's main small room. Kitchen downstairs, rock upstairs." },
  { name: "No Fun", city: "Albany, NY", capacity: 150, genres: ["Punk", "Indie", "Rock", "Metal"], pay: "$75-$300", booking_email: "booking@nofunalbany.com", type: "Bar/Venue", website: "https://www.nofunalbany.com", notes: "Tiny Albany punk bar. Very DIY, all-ages matinees." },
  { name: "The Haunt", city: "Ithaca, NY", capacity: 500, genres: ["Rock", "Indie", "Hip Hop", "EDM"], pay: "$200-$800", booking_email: "booking@thehaunt-ithaca.com", type: "Club", website: "https://www.thehaunt-ithaca.com", notes: "Ithaca's main club. Cornell and Ithaca College double market." },
  { name: "Bearsville Theater", city: "Woodstock, NY", capacity: 300, genres: ["Folk", "Indie", "Americana", "Rock"], pay: "$200-$700", booking_email: "booking@bearsvilletheater.com", type: "Concert Hall", website: "https://www.bearsvilletheater.com", notes: "Bearsville complex theater. Hudson Valley and Catskills market." },
  { name: "Caffe Lena", city: "Saratoga Springs, NY", capacity: 100, genres: ["Folk", "Singer-Songwriter", "Blues", "Americana"], pay: "$100-$400", booking_email: "booking@caffelena.org", type: "Arts Venue", website: "https://www.caffelena.org", notes: "America's oldest continuously running coffeehouse (1960). Songwriter mecca." },
  { name: "The Putnam Den", city: "Saratoga Springs, NY", capacity: 250, genres: ["Rock", "Jam", "Funk", "EDM"], pay: "$100-$500", booking_email: "booking@putnamden.com", type: "Club", website: "https://www.putnamden.com", notes: "Saratoga's late-night club. SPAC-season crowds pack this room." },
  { name: "The Chance", city: "Poughkeepsie, NY", capacity: 700, genres: ["Rock", "Metal", "Indie", "Hip Hop"], pay: "$250-$900", booking_email: "booking@thechanceinc.com", type: "Concert Hall", website: "https://www.thechanceinc.com", notes: "Poughkeepsie theater with four rooms. Mid-Hudson Valley touring hub." },
  { name: "The Anchor", city: "Kingston, NY", capacity: 250, genres: ["Indie", "Rock", "Folk", "Punk"], pay: "$100-$400", booking_email: "booking@theanchorkingston.com", type: "Bar/Venue", website: "https://www.theanchorkingston.com", notes: "Kingston dive bar with serious live music. Hudson Valley scene hub." },
  { name: "Mr. Roboto Project", city: "Pittsburgh, PA", capacity: 150, genres: ["Punk", "Indie", "Metal", "Rock"], pay: "$50-$250", booking_email: "booking@robotoproject.com", type: "Arts Venue", website: "https://www.robotoproject.com", notes: "Pittsburgh DIY all-ages cooperative. Hardcore punk institution." },
  { name: "Cattivo", city: "Pittsburgh, PA", capacity: 250, genres: ["Gothic", "Industrial", "Metal", "Indie"], pay: "$100-$400", booking_email: "booking@cattivopgh.com", type: "Club", website: "https://www.cattivopgh.com", notes: "Lawrenceville club with rooftop deck. Darker alternative bookings." },

  // ── North Carolina (expanded) ──
  { name: "The Blind Tiger", city: "Greensboro, NC", capacity: 300, genres: ["Rock", "Indie", "Jam", "Metal"], pay: "$150-$500", booking_email: "booking@theblindtiger.com", type: "Club", website: "https://www.theblindtiger.com", notes: "Greensboro rock institution since 1989. Strong touring stop." },
  { name: "The Ramkat", city: "Winston-Salem, NC", capacity: 400, genres: ["Rock", "Indie", "Americana", "Country"], pay: "$200-$700", booking_email: "booking@theramkat.com", type: "Concert Hall", website: "https://www.theramkat.com", notes: "Winston-Salem's flagship venue. Excellent sound and booking curation." },
  { name: "The Garage", city: "Winston-Salem, NC", capacity: 150, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$75-$300", booking_email: "booking@thegarage.ws", type: "Bar/Venue", website: "https://www.thegarage.ws", notes: "Small Winston-Salem room. Very supportive of emerging touring acts." },
  { name: "Greenfield Lake Amphitheater", city: "Wilmington, NC", capacity: 1000, genres: ["Indie", "Folk", "Americana", "Rock"], pay: "$300-$1200", booking_email: "booking@greenfieldlakeamp.com", type: "Amphitheater", website: "https://www.greenfieldlakeamp.com", notes: "Beautiful outdoor venue under cypress trees. Coastal NC market." },
  { name: "Bourgie Nights", city: "Wilmington, NC", capacity: 200, genres: ["Indie", "Rock", "Punk", "Hip Hop"], pay: "$75-$300", booking_email: "booking@bourgienights.com", type: "Club", website: "https://www.bourgienights.com", notes: "Downtown Wilmington club. Port City's underground room." },

  // ── North Dakota (expanded) ──
  { name: "The Laughing Sun", city: "Bismarck, ND", capacity: 200, genres: ["Folk", "Rock", "Indie", "Blues"], pay: "$100-$400", booking_email: "booking@laughingsunbrew.com", type: "Bar/Venue", website: "https://www.laughingsunbrew.com", notes: "Bismarck brewpub with live music. Capital city touring stop." },
  { name: "The District", city: "Sioux Falls, SD", capacity: 800, genres: ["Rock", "Indie", "Country", "Hip Hop"], pay: "$250-$1000", booking_email: "booking@thedistrictsf.com", type: "Concert Hall", website: "https://www.thedistrictsf.com", notes: "Sioux Falls' main mid-size room. Gateway to the Northern Plains run." },
  { name: "The Sanctuary", city: "Rapid City, SD", capacity: 200, genres: ["Rock", "Metal", "Indie", "Punk"], pay: "$75-$350", booking_email: "booking@thesanctuaryrc.com", type: "Club", website: "https://www.thesanctuaryrc.com", notes: "Black Hills rock room. Only indie venue for hundreds of miles." },

  // ── Ohio (expanded) ──
  { name: "Frankie's", city: "Toledo, OH", capacity: 300, genres: ["Rock", "Punk", "Indie", "Metal"], pay: "$100-$400", booking_email: "booking@frankiesinnercity.com", type: "Club", website: "https://www.frankiesinnercity.com", notes: "Toledo's rock club. Underground touring circuit in Northwest Ohio." },
  { name: "Gilly's", city: "Dayton, OH", capacity: 300, genres: ["Blues", "Rock", "Funk", "R&B"], pay: "$150-$500", booking_email: "booking@gillysdayton.com", type: "Club", website: "https://www.gillysdayton.com", notes: "Dayton blues room. Long-running intimate venue." },
  { name: "The Yellow Cab", city: "Dayton, OH", capacity: 300, genres: ["Indie", "Rock", "Folk", "Hip Hop"], pay: "$100-$400", booking_email: "booking@theyellowcab.org", type: "Arts Venue", website: "https://www.theyellowcab.org", notes: "Former taxi depot turned community venue. Stipend-friendly for touring acts." },
  { name: "Musica", city: "Akron, OH", capacity: 200, genres: ["Indie", "Rock", "Punk", "Hip Hop"], pay: "$100-$400", booking_email: "booking@musicaakron.com", type: "Club", website: "https://www.musicaakron.com", notes: "Akron's main club. Rubber City has a surprisingly deep music scene." },

  // ── Oklahoma (expanded) ──
  { name: "Cain's Ballroom", city: "Tulsa, OK", capacity: 1700, genres: ["Rock", "Country", "Punk", "Indie"], pay: "$500+", booking_email: "booking@cainsballroom.com", type: "Concert Hall", website: "https://www.cainsballroom.com", notes: "The historic home of Western Swing. Bob Wills, Sex Pistols, and everyone since." },
  { name: "The Vanguard", city: "Tulsa, OK", capacity: 400, genres: ["Indie", "Rock", "Hip Hop", "Pop"], pay: "$200-$800", booking_email: "booking@thevanguardtulsa.com", type: "Club", website: "https://www.thevanguardtulsa.com", notes: "Tulsa's premier small room. Listening-room format for touring acts." },
  { name: "Soundpony", city: "Tulsa, OK", capacity: 150, genres: ["Rock", "Punk", "Metal", "Indie"], pay: "$75-$300", booking_email: "booking@soundponybar.com", type: "Bar/Venue", website: "https://www.soundponybar.com", notes: "Bike bar with loud music. Tulsa's punk and metal clubhouse." },
  { name: "The Tower Theatre", city: "Oklahoma City, OK", capacity: 700, genres: ["Indie", "Rock", "Pop", "Hip Hop"], pay: "$250-$1000", booking_email: "booking@towertheatreokc.com", type: "Concert Hall", website: "https://www.towertheatreokc.com", notes: "Restored 1937 theater on Route 66. OKC's flagship independent room." },
  { name: "The Opolis", city: "Norman, OK", capacity: 250, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$100-$400", booking_email: "booking@theopolis.org", type: "Club", website: "https://www.theopolis.org", notes: "OU college town. Tiny room with an impeccable booking reputation." },
  { name: "VZD's", city: "Oklahoma City, OK", capacity: 250, genres: ["Rock", "Blues", "Jam", "Country"], pay: "$100-$400", booking_email: "booking@vzds.com", type: "Bar/Venue", website: "https://www.vzds.com", notes: "Classen Blvd institution since 1970s. Grateful Dead played the parking lot." },
  { name: "The Tumbleweed", city: "Stillwater, OK", capacity: 400, genres: ["Country", "Rock", "Red Dirt", "Americana"], pay: "$150-$600", booking_email: "booking@tumbleweedok.com", type: "Club", website: "https://www.tumbleweedok.com", notes: "The home of Red Dirt music. OSU college market, dancehall crowds." },

  // ── Oregon (expanded) ──
  { name: "The Pentacle Theatre", city: "Salem, OR", capacity: 300, genres: ["Rock", "Indie", "Metal", "Punk"], pay: "$100-$400", booking_email: "booking@pentaclesalem.com", type: "Club", website: "https://www.pentaclesalem.com", notes: "Salem's rock room. Willamette Valley touring stop." },
  { name: "The Domino Room", city: "Bend, OR", capacity: 200, genres: ["Indie", "Rock", "Folk", "Jam"], pay: "$100-$400", booking_email: "booking@dominoroom.com", type: "Club", website: "https://www.dominoroom.com", notes: "Bend's small room. Central Oregon mountain-town market." },
  { name: "The Shakedown", city: "Bellingham, WA", capacity: 300, genres: ["Indie", "Rock", "Punk", "EDM"], pay: "$100-$400", booking_email: "booking@shakedownst.com", type: "Bar/Venue", website: "https://www.shakedownst.com", notes: "Bellingham's main club. WWU college market on the Seattle-Vancouver route." },
  { name: "The Wild Buffalo", city: "Bellingham, WA", capacity: 400, genres: ["Rock", "Indie", "Jam", "Hip Hop"], pay: "$150-$600", booking_email: "booking@wildbuffalo.net", type: "Club", website: "https://www.wildbuffalo.net", notes: "Bellingham's larger room. National touring acts between Seattle and BC." },
  { name: "Jazzbones", city: "Tacoma, WA", capacity: 400, genres: ["Rock", "Metal", "Indie", "Hip Hop"], pay: "$150-$600", booking_email: "booking@jazzbonestacoma.com", type: "Club", website: "https://www.jazzbonestacoma.com", notes: "Tacoma's main club. Halfway between Seattle and Portland." },
  { name: "Bob's Java Jive", city: "Tacoma, WA", capacity: 150, genres: ["Punk", "Rock", "Indie", "Metal"], pay: "$50-$250", booking_email: "booking@bobsjavajive.com", type: "Bar/Venue", website: "https://www.bobsjavajive.com", notes: "Tiki-hut dive shaped like a coffee pot. Punk institution since 1929." },
  { name: "The Capitol Theater", city: "Olympia, WA", capacity: 800, genres: ["Rock", "Indie", "Punk", "Folk"], pay: "$250-$900", booking_email: "booking@capitoltheater.org", type: "Concert Hall", website: "https://www.capitoltheater.org", notes: "Olympia's 1924 theater. K Records heritage — riot grrrl history lives here." },

  // ── Pennsylvania (expanded) ──
  { name: "The Chameleon Club", city: "Lancaster, PA", capacity: 600, genres: ["Rock", "Metal", "Indie", "Hip Hop"], pay: "$200-$800", booking_email: "booking@lancasterchameleon.com", type: "Club", website: "https://www.lancasterchameleon.com", notes: "Lancaster's main venue. Four rooms in one club, all-ages shows." },
  { name: "Godfrey Daniels", city: "Bethlehem, PA", capacity: 100, genres: ["Folk", "Singer-Songwriter", "Blues", "Americana"], pay: "$100-$400", booking_email: "booking@godfreydaniels.org", type: "Arts Venue", website: "https://www.godfreydaniels.org", notes: "Legendary Bethlehem listening club since 1976. The Lehigh Valley's folk mecca." },
  { name: "The Phyrst", city: "State College, PA", capacity: 150, genres: ["Rock", "Indie", "Punk", "Folk"], pay: "$75-$300", booking_email: "booking@thephryst.com", type: "Bar/Venue", website: "https://www.thephryst.com", notes: "Penn State college town basement bar. Happy Valley's rock room." },
  { name: "Scranton Cultural Center", city: "Scranton, PA", capacity: 300, genres: ["Indie", "Rock", "Folk", "Pop"], pay: "$200-$800", booking_email: "booking@scrantonculturalcenter.org", type: "Arts Venue", website: "https://www.scrantonculturalcenter.org", notes: "Mansion-turned-venue. Northeastern PA touring stop." },

  // ── Rhode Island (expanded) ──
  { name: "The Columbus Theatre", city: "Providence, RI", capacity: 350, genres: ["Indie", "Rock", "Folk", "Punk"], pay: "$150-$500", booking_email: "booking@columbustheatre.com", type: "Concert Hall", website: "https://www.columbustheatre.com", notes: "Restored 1926 theater. Providence's favorite mid-small room." },

  // ── South Carolina (expanded) ──
  { name: "New Brookland Tavern", city: "West Columbia, SC", capacity: 200, genres: ["Indie", "Rock", "Punk", "Hip Hop"], pay: "$100-$350", booking_email: "booking@newbrooklandtavern.com", type: "Bar/Venue", website: "https://www.newbrooklandtavern.com", notes: "Columbia SC's indie room. USC market." },
  { name: "Tin Roof", city: "Columbia, SC", capacity: 300, genres: ["Country", "Rock", "Pop", "Americana"], pay: "$150-$500", booking_email: "booking@tinroofcolumbia.com", type: "Bar/Venue", website: "https://www.tinroofcolumbia.com", notes: "Vista district bar with nightly live music. Party-friendly crowds." },
  { name: "The Radio Room", city: "Greenville, SC", capacity: 250, genres: ["Indie", "Rock", "Metal", "Punk"], pay: "$100-$400", booking_email: "booking@theradioroomgvl.com", type: "Club", website: "https://www.theradioroomgvl.com", notes: "Greenville's rock club. Upstate SC touring stop." },
  { name: "House of Blues Myrtle Beach", city: "North Myrtle Beach, SC", capacity: 2000, genres: ["Rock", "Country", "Pop", "R&B"], pay: "$500+", booking_email: "booking@hobmyrtlebeach.com", type: "Concert Hall", website: "https://www.houseofblues.com/myrtle-beach", notes: "Beach market venue. Strong summer season with tourist crowds." },

  // ── Tennessee (expanded) ──
  { name: "The Bijou Theatre", city: "Knoxville, TN", capacity: 700, genres: ["Rock", "Indie", "Folk", "Americana"], pay: "$250-$1000", booking_email: "booking@knoxbijou.com", type: "Concert Hall", website: "https://www.knoxbijou.com", notes: "1909 theater in Old City. Knoxville's most beautiful mid-size room." },
  { name: "The Mill & Mine", city: "Knoxville, TN", capacity: 500, genres: ["Indie", "Rock", "EDM", "Hip Hop"], pay: "$200-$900", booking_email: "booking@themillandmine.com", type: "Concert Hall", website: "https://www.themillandmine.com", notes: "Converted industrial space. Knoxville's modern touring room." },
  { name: "The Pilot Light", city: "Knoxville, TN", capacity: 100, genres: ["Punk", "Indie", "Metal", "Rock"], pay: "$50-$200", booking_email: "booking@thepilotlight.com", type: "Bar/Venue", website: "https://www.thepilotlight.com", notes: "Tiny Old City dive. Knoxville's underground institution." },
  { name: "The Signal", city: "Chattanooga, TN", capacity: 800, genres: ["Rock", "Indie", "Pop", "Hip Hop"], pay: "$300-$1200", booking_email: "booking@thesignaltn.com", type: "Concert Hall", website: "https://www.thesignaltn.com", notes: "Chattanooga's flagship venue. Southside district, excellent production." },
  { name: "Songbirds", city: "Chattanooga, TN", capacity: 200, genres: ["Rock", "Americana", "Indie", "Country"], pay: "$100-$400", booking_email: "booking@songbirds.org", type: "Arts Venue", website: "https://www.songbirds.org", notes: "Guitar-museum venue with a small stage. Chattanooga's listening room." },

  // ── Texas (expanded) ──
  { name: "The Blue Light Live", city: "Lubbock, TX", capacity: 400, genres: ["Country", "Red Dirt", "Rock", "Americana"], pay: "$150-$600", booking_email: "booking@thebluelightlive.com", type: "Club", website: "https://www.thebluelightlive.com", notes: "The home of Texas Red Dirt music. Buddy Holly's hometown market." },
  { name: "The Grand 1894 Opera House", city: "Galveston, TX", capacity: 800, genres: ["Folk", "Indie", "Americana", "Pop"], pay: "$300-$1200", booking_email: "booking@thegrand.com", type: "Concert Hall", website: "https://www.thegrand.com", notes: "Oldest opera house in Texas. Historic island beach-town market." },
  { name: "Rubber Gloves Rehearsal Studios", city: "Denton, TX", capacity: 200, genres: ["Indie", "Punk", "Rock", "Experimental"], pay: "$75-$300", booking_email: "booking@rubberglovesdenton.com", type: "Bar/Venue", website: "https://www.rubberglovesdenton.com", notes: "Denton DIY institution. UNT's legendary music scene lives here." },
  { name: "Dan's Silverleaf", city: "Denton, TX", capacity: 300, genres: ["Indie", "Folk", "Americana", "Jam"], pay: "$100-$400", booking_email: "booking@danssilverleaf.com", type: "Bar/Venue", website: "https://www.danssilverleaf.com", notes: "Denton listening room. Booked by music lovers, for music lovers." },
  { name: "Tannahill's Tavern & Music Hall", city: "Fort Worth, TX", capacity: 700, genres: ["Country", "Rock", "Americana", "Red Dirt"], pay: "$250-$1000", booking_email: "booking@tannahills.com", type: "Concert Hall", website: "https://www.tannahills.com", notes: "Fort Worth's Stockyards-adjacent hall. Modern country and Red Dirt crowd." },
  { name: "The Grotto", city: "Fort Worth, TX", capacity: 150, genres: ["Rock", "Punk", "Metal", "Indie"], pay: "$75-$300", booking_email: "booking@thegrottofortworth.com", type: "Bar/Venue", website: "https://www.thegrottofortworth.com", notes: "Near South Side dive. Fort Worth's underground rock bar." },

  // ── Utah (expanded) ──
  { name: "Velour Live Music Gallery", city: "Provo, UT", capacity: 200, genres: ["Indie", "Rock", "Pop", "Folk"], pay: "$100-$400", booking_email: "booking@velourlive.com", type: "Club", website: "https://www.velourlive.com", notes: "Provo's famous incubator. Imagine Dragons and Neon Trees played here first." },
  { name: "The State Room", city: "Salt Lake City, UT", capacity: 400, genres: ["Indie", "Rock", "Folk", "Country"], pay: "$200-$800", booking_email: "booking@thestateroomslc.com", type: "Concert Hall", website: "https://www.thestateroomslc.com", notes: "SLC listening room with an all-ages ethos and great sound." },

  // ── Vermont (expanded) ──
  { name: "ArtsRiot", city: "Burlington, VT", capacity: 250, genres: ["Indie", "Rock", "Punk", "Hip Hop"], pay: "$100-$400", booking_email: "booking@artsriot.com", type: "Arts Venue", website: "https://www.artsriot.com", notes: "Burlington's underground venue. Funk jams and indie touring alike." },
  { name: "The Stone Church", city: "Brattleboro, VT", capacity: 200, genres: ["Folk", "Indie", "Americana", "Rock"], pay: "$100-$400", booking_email: "booking@thestonechurchvt.com", type: "Arts Venue", website: "https://www.thestonechurchvt.com", notes: "1868 church turned venue. Southern Vermont listening room." },

  // ── Virginia (expanded) ──
  { name: "The Spot on Kirk", city: "Roanoke, VA", capacity: 250, genres: ["Indie", "Folk", "Jazz", "Americana"], pay: "$150-$500", booking_email: "booking@thespotonkirk.com", type: "Club", website: "https://www.thespotonkirk.com", notes: "Roanoke's listening room. Blue Ridge market with real music appetite." },
  { name: "The Lyric Theatre", city: "Blacksburg, VA", capacity: 150, genres: ["Indie", "Folk", "Rock", "Country"], pay: "$100-$350", booking_email: "booking@thelyric.com", notes: "Virginia Tech college town. Converted 1909 movie theater.", type: "Arts Venue", website: "https://www.thelyric.com" },
  { name: "The Golden Pony", city: "Harrisonburg, VA", capacity: 150, genres: ["Indie", "Rock", "Punk", "Folk"], pay: "$75-$300", booking_email: "booking@thegoldenpony.com", type: "Bar/Venue", website: "https://www.thegoldenpony.com", notes: "JMU college town. Shenandoah Valley's indie rock bar." },

  // ── Washington DC / Maryland metro (expanded) ──
  { name: "The Atlantis", city: "Washington, DC", capacity: 450, genres: ["Rock", "Indie", "Pop", "Hip Hop"], pay: "$250-$1000", booking_email: "booking@theatlantisdc.com", type: "Concert Hall", website: "https://www.theatlantisdc.com", notes: "9:30 Club's new sibling, a replica of the original 1979 room. Career-mileage venue." },

  // ── West Virginia ──
  { name: "Black Bear Burritos", city: "Morgantown, WV", capacity: 200, genres: ["Indie", "Rock", "Folk", "Jam"], pay: "$75-$300", booking_email: "booking@blackbearburritos.com", type: "Bar/Venue", website: "https://www.blackbearburritos.com", notes: "WVU college town. Burritos and bands in downtown Morgantown." },
  { name: "The Empty Glass", city: "Charleston, WV", capacity: 200, genres: ["Rock", "Blues", "Jam", "Indie"], pay: "$75-$300", booking_email: "booking@theemptyglass.com", type: "Bar/Venue", website: "https://www.theemptyglass.com", notes: "Charleston WV's rock club. The state's only true touring venue." },

  // ── Wisconsin (expanded) ──
  { name: "The Plus", city: "Eau Claire, WI", capacity: 200, genres: ["Indie", "Folk", "Rock", "Hip Hop"], pay: "$100-$350", booking_email: "booking@theplusec.com", type: "Arts Venue", website: "https://www.theplusec.com", notes: "Eau Claire's indie hub. Bon Iver's hometown scene." },

  // ── Wyoming ──
  { name: "The Lincoln", city: "Cheyenne, WY", capacity: 200, genres: ["Rock", "Indie", "Country", "Folk"], pay: "$100-$400", booking_email: "booking@thelincolncheyenne.com", type: "Bar/Venue", website: "https://www.thelincolncheyenne.com", notes: "Cheyenne's rock bar. Front Range touring stop between Denver and Omaha." },
  { name: "The Rose", city: "Jackson, WY", capacity: 250, genres: ["Rock", "Indie", "Americana", "Folk"], pay: "$150-$500", booking_email: "booking@therosejacksonhole.com", type: "Club", website: "https://www.therosejacksonhole.com", notes: "Jackson Hole's live room. Mountain-town crowds and high ticket prices." },
];