import { useState } from "react";
import { Download, Play, Clock, Film, Type, Palette, Zap, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";

const VIBE_GRADIENTS = {
  aggressive: "from-red-950/80 via-gray-950/60 to-black/90",
  emotional: "from-blue-950/80 via-slate-900/60 to-black/90",
  confident: "from-yellow-950/60 via-gray-900/60 to-black/90",
  storytelling: "from-teal-950/60 via-gray-900/60 to-black/90",
};

const TEXT_STYLE_BADGES = {
  bold_caption: { label: "Bold Caption", color: "text-yellow-400 bg-yellow-500/10 border-yellow-500/20" },
  timed_lyric: { label: "Timed Lyric", color: "text-blue-400 bg-blue-500/10 border-blue-500/20" },
  minimal_quote: { label: "Minimal Quote", color: "text-teal-400 bg-teal-500/10 border-teal-500/20" },
};

const MOOD_BAR_COLOR = (score) => {
  if (score >= 8) return "bg-primary";
  if (score >= 6) return "bg-chart-4";
  return "bg-chart-5";
};

// Vertical phone mockup with simulated clip preview
function ClipPreview({ clip, vibe }) {
  const gradient = VIBE_GRADIENTS[vibe] || VIBE_GRADIENTS.confident;
  const textStyle = clip.text_style;

  return (
    <div className="relative mx-auto w-[120px] h-[213px] rounded-2xl overflow-hidden border border-border shadow-xl bg-black flex-shrink-0">
      {/* Background gradient simulating cinematic footage */}
      <div className={`absolute inset-0 bg-gradient-to-b ${gradient}`} />

      {/* Simulated footage texture */}
      <div className="absolute inset-0 opacity-20"
        style={{
          backgroundImage: `radial-gradient(circle at 30% 40%, rgba(255,255,255,0.08) 0%, transparent 60%), 
                            radial-gradient(circle at 70% 60%, rgba(255,255,255,0.05) 0%, transparent 50%)`,
        }}
      />

      {/* Footage tags as pills */}
      <div className="absolute top-2 left-2 right-2 flex flex-wrap gap-0.5">
        {(clip.footage_tags || []).slice(0, 2).map((tag) => (
          <span key={tag} className="text-[7px] px-1.5 py-0.5 rounded-full bg-black/50 text-white/60 backdrop-blur-sm">
            {tag}
          </span>
        ))}
      </div>

      {/* Duration badge */}
      <div className="absolute top-2 right-2 flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-black/60 backdrop-blur-sm">
        <Clock className="h-2 w-2 text-white/70" />
        <span className="text-[8px] text-white/70">{clip.duration}s</span>
      </div>

      {/* Play button overlay */}
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="h-10 w-10 rounded-full bg-white/10 border border-white/20 backdrop-blur-sm flex items-center justify-center">
          <Play className="h-4 w-4 text-white fill-white ml-0.5" />
        </div>
      </div>

      {/* Lyric overlay simulation */}
      <div className={`absolute bottom-6 left-2 right-2 text-center ${
        textStyle === "bold_caption" ? "font-black text-white text-[9px] leading-tight tracking-tight" :
        textStyle === "timed_lyric" ? "font-bold text-white text-[8px] leading-tight" :
        "font-light text-white/90 text-[8px] italic leading-tight"
      }`}>
        <div className={`inline-block px-1.5 py-1 rounded ${
          textStyle === "bold_caption" ? "bg-black/70" :
          textStyle === "timed_lyric" ? "bg-transparent" :
          "bg-transparent"
        }`}>
          {clip.lyric_overlay?.split(" ").slice(0, 6).join(" ")}...
        </div>
      </div>

      {/* TikTok-style bottom gradient */}
      <div className="absolute bottom-0 inset-x-0 h-16 bg-gradient-to-t from-black/80 to-transparent" />

      {/* Color grade indicator */}
      <div className="absolute bottom-1 left-2 right-2">
        <p className="text-[6px] text-white/40 text-center truncate">{clip.color_grade?.split(",")[0]}</p>
      </div>
    </div>
  );
}

export default function ClipCard({ clip, vibe, index }) {
  const [expanded, setExpanded] = useState(false);
  const textBadge = TEXT_STYLE_BADGES[clip.text_style] || TEXT_STYLE_BADGES.bold_caption;

  const handleDownload = () => {
    // Generate a text file with the full clip brief (since we can't generate actual video)
    const content = `CONTENT ENGINE — CLIP ${index + 1}
${"=".repeat(50)}
Title: ${clip.title}
Duration: ${clip.duration} seconds
Hook Section: ${clip.hook_section}
Vibe: ${vibe}

VISUALS
Visual Style: ${clip.visual_style}
Footage Tags: ${(clip.footage_tags || []).join(", ")}
Color Grade: ${clip.color_grade}
Motion Style: ${clip.motion_style}

TEXT OVERLAY
Style: ${clip.text_style_label}
Lyric: "${clip.lyric_overlay}"

UNIQUE ANGLE
${clip.unique_angle}

Mood Score: ${clip.mood_score}/10
Generated by SoundReady Content Engine`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `clip_${index + 1}_${vibe}_brief.txt`;
    a.click();
  };

  return (
    <div className="rounded-2xl bg-card border border-border overflow-hidden hover:border-primary/25 transition-colors">
      <div className="p-4 space-y-4">
        {/* Header */}
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap mb-1">
              <span className="text-xs font-bold text-muted-foreground">CLIP {index + 1}</span>
              <span className={`text-xs px-2 py-0.5 rounded-full font-medium border ${textBadge.color}`}>
                {textBadge.label}
              </span>
            </div>
            <p className="font-heading font-bold text-base leading-tight">{clip.title}</p>
            <p className="text-xs text-muted-foreground mt-0.5 flex items-center gap-1.5">
              <Clock className="h-3 w-3" />{clip.duration}s · Hook {clip.hook_section}
            </p>
          </div>
          {/* Mood score */}
          <div className="text-center shrink-0">
            <p className="font-heading font-black text-2xl text-primary">{clip.mood_score}</p>
            <p className="text-[10px] text-muted-foreground">/ 10</p>
          </div>
        </div>

        {/* Preview + key details */}
        <div className="flex gap-4 items-start">
          <ClipPreview clip={clip} vibe={vibe} />

          <div className="flex-1 space-y-3 min-w-0">
            {/* Visual style */}
            <div className="space-y-1">
              <p className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wide flex items-center gap-1">
                <Film className="h-3 w-3" /> Visual
              </p>
              <p className="text-xs text-foreground/85 leading-relaxed">{clip.visual_style}</p>
            </div>

            {/* Lyric overlay */}
            <div className="space-y-1">
              <p className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wide flex items-center gap-1">
                <Type className="h-3 w-3" /> Overlay
              </p>
              <p className="text-xs italic text-foreground/80 leading-relaxed line-clamp-2">"{clip.lyric_overlay}"</p>
            </div>

            {/* Color grade */}
            <div className="space-y-1">
              <p className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wide flex items-center gap-1">
                <Palette className="h-3 w-3" /> Grade
              </p>
              <p className="text-xs text-foreground/80">{clip.color_grade}</p>
            </div>
          </div>
        </div>

        {/* Mood bar */}
        <div className="space-y-1">
          <div className="flex items-center justify-between text-[10px] text-muted-foreground">
            <span>Mood intensity</span>
            <span>{clip.mood_score}/10</span>
          </div>
          <div className="h-1.5 rounded-full bg-secondary overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${(clip.mood_score / 10) * 100}%` }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className={`h-full rounded-full ${MOOD_BAR_COLOR(clip.mood_score)}`}
            />
          </div>
        </div>

        {/* Expandable details */}
        <button
          className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors w-full"
          onClick={() => setExpanded(!expanded)}
        >
          {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
          {expanded ? "Less detail" : "Full clip brief"}
        </button>

        {expanded && (
          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="space-y-3 pt-2 border-t border-border">
            {/* Footage tags */}
            <div className="space-y-1.5">
              <p className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wide">Footage Tags</p>
              <div className="flex flex-wrap gap-1.5">
                {(clip.footage_tags || []).map((tag) => (
                  <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-secondary border border-border text-foreground/80">{tag}</span>
                ))}
              </div>
            </div>

            {/* Motion style */}
            <div className="space-y-1">
              <p className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wide">Motion Style</p>
              <p className="text-xs text-foreground/80">{clip.motion_style}</p>
            </div>

            {/* Unique angle */}
            <div className="flex items-start gap-2 p-3 rounded-xl bg-primary/5 border border-primary/15">
              <Zap className="h-3.5 w-3.5 text-primary shrink-0 mt-0.5" />
              <p className="text-xs text-foreground/85 leading-relaxed">{clip.unique_angle}</p>
            </div>
          </motion.div>
        )}
      </div>

      {/* Download button */}
      <div className="px-4 pb-4">
        <Button variant="outline" size="sm" className="w-full gap-2 text-xs" onClick={handleDownload}>
          <Download className="h-3.5 w-3.5" />
          Download Clip Brief
        </Button>
      </div>
    </div>
  );
}