import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, FileText, Sparkles, Loader2, Download, Tag, Music, Newspaper } from "lucide-react";
import { Button } from "@/components/ui/button";
import { jsPDF } from "jspdf";

function Section({ title, children }) {
  return (
    <div className="rounded-xl bg-secondary/50 border border-border p-4 space-y-2">
      <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">{title}</p>
      {children}
    </div>
  );
}

function TagCloud({ tags = [], color = "primary" }) {
  const cls = color === "accent" ? "bg-accent/10 text-accent" : "bg-primary/10 text-primary";
  return (
    <div className="flex flex-wrap gap-2">
      {tags.map((t) => <span key={t} className={`px-3 py-1 rounded-full text-sm font-medium ${cls}`}>{t}</span>)}
    </div>
  );
}

function generatePitchPDF(analysis, pitchData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, margin = 20;
  let y = 20;

  // Header bar
  doc.setFillColor(100, 50, 200);
  doc.rect(0, 0, W, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("SOUNDSCORE — PLAYLIST PITCH PACKAGE", margin, 8);
  doc.text(new Date().toLocaleDateString(), W - margin, 8, { align: "right" });

  y = 28;
  doc.setTextColor(10, 10, 20);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(analysis.title, margin, y);
  y += 10;
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 100);
  doc.text(`${analysis.artist_name}  ·  ${analysis.genre}`, margin, y);
  y += 6;
  doc.setFontSize(11);
  doc.text(`Mood: ${analysis.mood || "—"}  ·  Energy: ${analysis.energy_level || "—"}  ·  BPM: ~${analysis.bpm_estimate || "?"}`, margin, y);

  // Divider
  y += 8;
  doc.setDrawColor(220, 220, 230);
  doc.line(margin, y, W - margin, y);
  y += 10;

  // Algorithm Score
  doc.setFillColor(245, 243, 255);
  doc.roundedRect(margin, y, W - margin * 2, 18, 3, 3, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100, 50, 200);
  doc.text(`SoundScore: ${analysis.overall_score}/100`, margin + 6, y + 12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 100);
  doc.text(`Spotify: ${analysis.spotify_score}  ·  Apple: ${analysis.apple_music_score}  ·  TikTok: ${analysis.tiktok_score}`, margin + 80, y + 12);
  y += 26;

  // Pitch paragraph
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("Curator Pitch", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 70);
  const pitchLines = doc.splitTextToSize(pitchData.pitch_paragraph || "", W - margin * 2);
  doc.text(pitchLines, margin, y);
  y += pitchLines.length * 5 + 10;

  // Tags
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("DSP Mood & Genre Tags", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 50, 200);
  doc.text((pitchData.dsp_tags || []).join("   ·   "), margin, y);
  y += 12;

  // Similar artists
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("Sounds Like", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 70);
  doc.text((pitchData.similar_artists || []).join("  ·  "), margin, y);
  y += 12;

  // Target playlist
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("Target Playlist Category", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 70);
  doc.text(pitchData.target_playlist_category || "—", margin, y);
  y += 14;

  // Footer
  doc.setDrawColor(220, 220, 230);
  doc.line(margin, y, W - margin, y);
  y += 7;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 170);
  doc.text("Generated by SoundScore · soundscore.app", margin, y);

  doc.save(`${analysis.title}_pitch_package.pdf`);
}

function generatePressPDF(analysis, pressData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, margin = 20;
  let y = 20;

  doc.setFillColor(20, 184, 166);
  doc.rect(0, 0, W, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("SOUNDSCORE — ELECTRONIC PRESS KIT", margin, 8);
  doc.text(new Date().toLocaleDateString(), W - margin, 8, { align: "right" });

  y = 28;
  doc.setTextColor(10, 10, 20);
  doc.setFontSize(26);
  doc.setFont("helvetica", "bold");
  doc.text(analysis.title, margin, y);
  y += 9;
  doc.setFontSize(15);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 100);
  doc.text(analysis.artist_name, margin, y);
  y += 8;
  doc.setDrawColor(220, 220, 230);
  doc.line(margin, y, W - margin, y);
  y += 10;

  // Song details
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 70);
  const details = [
    ["Genre", analysis.genre],
    ["Mood", analysis.mood],
    ["Energy", analysis.energy_level],
    ["Tempo", `~${analysis.bpm_estimate} BPM`],
    ["SoundScore", `${analysis.overall_score}/100`],
  ];
  details.forEach(([k, v]) => {
    doc.setFont("helvetica", "bold");
    doc.text(k + ":", margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(v || "—", margin + 30, y);
    y += 7;
  });
  y += 4;

  // Bio
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("Artist Bio", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 70);
  const bioLines = doc.splitTextToSize(pressData.bio_placeholder || "", W - margin * 2);
  doc.text(bioLines, margin, y);
  y += bioLines.length * 5 + 10;

  // Quote / Press Line
  if (pressData.press_quote) {
    doc.setFillColor(245, 253, 252);
    doc.roundedRect(margin, y, W - margin * 2, 20, 3, 3, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(20, 120, 110);
    const qLines = doc.splitTextToSize(`"${pressData.press_quote}"`, W - margin * 2 - 12);
    doc.text(qLines, margin + 6, y + 8);
    y += 28;
  }

  // Similar artists
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("Sounds Like", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 70);
  doc.text((analysis.similar_artists || []).join("  ·  "), margin, y);
  y += 12;

  // Best clip
  if (pressData.best_clip_timestamp) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(10, 10, 20);
    doc.text("Best Social Clip", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 70);
    doc.text(`Timestamp: ${pressData.best_clip_timestamp}`, margin, y);
    y += 6;
    const clipLines = doc.splitTextToSize(pressData.best_clip_reason || "", W - margin * 2);
    doc.text(clipLines, margin, y);
    y += clipLines.length * 5 + 10;
  }

  // Mood tags
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(10, 10, 20);
  doc.text("Mood & Genre Descriptors", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 70);
  doc.text((pressData.mood_tags || []).join("  ·  "), margin, y);
  y += 14;

  doc.setDrawColor(220, 220, 230);
  doc.line(margin, y, W - margin, y);
  y += 7;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 170);
  doc.text("Generated by SoundScore · soundscore.app", margin, y);

  doc.save(`${analysis.title}_press_sheet.pdf`);
}

export default function PitchPackage() {
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("pitch");
  const [generating, setGenerating] = useState(false);
  const [pitchData, setPitchData] = useState(null);
  const [pressData, setPressData] = useState(null);

  const urlParams = new URLSearchParams(window.location.search);
  const id = urlParams.get("id");

  useEffect(() => {
    if (!id) return;
    base44.entities.SongAnalysis.filter({ id }).then((items) => {
      setAnalysis(items[0] || null);
      setLoading(false);
    });
  }, [id]);

  const generatePitch = async () => {
    setGenerating(true);
    const result = await base44.integrations.Core.InvokeLLM({
      prompt: `You are a professional music curator submission writer. Create a complete playlist pitch package for this song.

Title: "${analysis.title}"
Artist: ${analysis.artist_name}
Genre: ${analysis.genre}
Mood: ${analysis.mood}
Energy: ${analysis.energy_level}
BPM: ${analysis.bpm_estimate}
Similar Artists: ${(analysis.similar_artists || []).join(", ")}
Strengths: ${(analysis.strengths || []).join(", ")}
TikTok Score: ${analysis.tiktok_score}, Spotify Score: ${analysis.spotify_score}

Write the pitch paragraph in the style of a professional curator submission — first person from the artist, compelling, concise (3-4 sentences). Be specific to this song's feel.`,
      response_json_schema: {
        type: "object",
        properties: {
          pitch_paragraph: { type: "string" },
          dsp_tags: { type: "array", items: { type: "string" }, description: "8-10 exact mood and genre tags for DSP submission" },
          similar_artists: { type: "array", items: { type: "string" }, description: "5 similar artists for pitching and targeting" },
          target_playlist_category: { type: "string", description: "Specific playlist category e.g. 'Late Night R&B', 'Workout Rap'" },
          submission_tips: { type: "array", items: { type: "string" }, description: "3 specific tips for submitting this song to playlists" },
        }
      }
    });
    setPitchData(result);
    setGenerating(false);
  };

  const generatePressSheet = async () => {
    setGenerating(true);
    const result = await base44.integrations.Core.InvokeLLM({
      prompt: `You are a music publicist creating an EPK press sheet. Generate content for this song:

Title: "${analysis.title}"
Artist: ${analysis.artist_name}
Genre: ${analysis.genre}
Mood: ${analysis.mood}
Energy: ${analysis.energy_level}
Similar Artists: ${(analysis.similar_artists || []).join(", ")}
Strengths: ${(analysis.strengths || []).join(", ")}
Recommendations: ${(analysis.recommendations || []).join(", ")}

The bio should be a compelling 3-sentence placeholder that captures the artist's sound and this song's energy. The press quote should sound like a real music blog excerpt. Be specific and evocative, not generic.`,
      response_json_schema: {
        type: "object",
        properties: {
          bio_placeholder: { type: "string", description: "3-sentence artist bio placeholder" },
          press_quote: { type: "string", description: "One compelling pull-quote about the song as if from a music blog" },
          best_clip_timestamp: { type: "string", description: "Best 15-30 second clip e.g. '0:47 - 1:12'" },
          best_clip_reason: { type: "string", description: "1-2 sentences why this is the best clip" },
          mood_tags: { type: "array", items: { type: "string" }, description: "6-8 mood and descriptive tags" },
          contact_placeholder: { type: "string", description: "e.g. 'booking@artistname.com'" },
        }
      }
    });
    setPressData(result);
    setGenerating(false);
  };

  if (loading) return <div className="flex justify-center py-32"><Loader2 className="h-8 w-8 text-primary animate-spin" /></div>;

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="flex items-center gap-3">
        <Link to={`/song?id=${id}`} className="h-9 w-9 rounded-xl bg-secondary flex items-center justify-center hover:bg-secondary/80 transition-colors">
          <ArrowLeft className="h-4 w-4" />
        </Link>
        <div>
          <p className="text-xs text-muted-foreground uppercase tracking-widest">Pitch & Press</p>
          <h1 className="font-heading text-2xl font-bold">{analysis?.title}</h1>
        </div>
      </motion.div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 bg-secondary rounded-xl w-fit">
        {[
          { key: "pitch", label: "Playlist Pitch", icon: Music },
          { key: "press", label: "Press Sheet (EPK)", icon: Newspaper },
        ].map(({ key, label, icon: Icon }) => (
          <button key={key} onClick={() => setActiveTab(key)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
              activeTab === key ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"
            }`}>
            <Icon className="h-4 w-4" />{label}
          </button>
        ))}
      </div>

      <AnimatePresence mode="wait">
        {activeTab === "pitch" && (
          <motion.div key="pitch" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-4">
            {!pitchData ? (
              <div className="rounded-2xl bg-card border border-border p-10 text-center">
                <Music className="h-12 w-12 text-primary mx-auto mb-4 opacity-50" />
                <h3 className="font-heading font-semibold text-lg mb-2">Generate Your Pitch Package</h3>
                <p className="text-sm text-muted-foreground mb-6 max-w-sm mx-auto">
                  A complete curator submission package — pitch paragraph, DSP tags, similar artists, and target playlist category. Ready to send.
                </p>
                <Button onClick={generatePitch} disabled={generating} className="gap-2">
                  {generating ? <><Loader2 className="h-4 w-4 animate-spin" />Generating...</> : <><Sparkles className="h-4 w-4" />Generate Pitch Package</>}
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                <Section title="Curator Pitch Paragraph">
                  <p className="text-sm leading-relaxed">{pitchData.pitch_paragraph}</p>
                </Section>
                <Section title="DSP Mood & Genre Tags">
                  <TagCloud tags={pitchData.dsp_tags} color="primary" />
                </Section>
                <Section title="Sounds Like">
                  <TagCloud tags={pitchData.similar_artists} color="accent" />
                </Section>
                <Section title="Target Playlist Category">
                  <p className="text-sm font-medium text-foreground">{pitchData.target_playlist_category}</p>
                </Section>
                {pitchData.submission_tips?.length > 0 && (
                  <Section title="Submission Tips">
                    <ul className="space-y-2">
                      {pitchData.submission_tips.map((t, i) => (
                        <li key={i} className="text-sm text-muted-foreground flex gap-2">
                          <span className="text-primary font-bold shrink-0">{i + 1}.</span>{t}
                        </li>
                      ))}
                    </ul>
                  </Section>
                )}
                <div className="flex gap-3 pt-2">
                  <Button onClick={() => generatePitchPDF(analysis, pitchData)} className="gap-2">
                    <Download className="h-4 w-4" />Download PDF
                  </Button>
                  <Button variant="outline" onClick={generatePitch} disabled={generating} size="sm" className="gap-2">
                    <Sparkles className="h-3.5 w-3.5" />Regenerate
                  </Button>
                </div>
              </div>
            )}
          </motion.div>
        )}

        {activeTab === "press" && (
          <motion.div key="press" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-4">
            {!pressData ? (
              <div className="rounded-2xl bg-card border border-border p-10 text-center">
                <Newspaper className="h-12 w-12 text-primary mx-auto mb-4 opacity-50" />
                <h3 className="font-heading font-semibold text-lg mb-2">Generate Your Press Sheet</h3>
                <p className="text-sm text-muted-foreground mb-6 max-w-sm mx-auto">
                  A clean, professional EPK-style press sheet for the single — ready to send to blogs, curators, and press contacts.
                </p>
                <Button onClick={generatePressSheet} disabled={generating} className="gap-2">
                  {generating ? <><Loader2 className="h-4 w-4 animate-spin" />Generating...</> : <><Sparkles className="h-4 w-4" />Generate Press Sheet</>}
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                <Section title="Artist Bio (Placeholder)">
                  <p className="text-sm leading-relaxed">{pressData.bio_placeholder}</p>
                </Section>
                {pressData.press_quote && (
                  <Section title="Press Quote">
                    <p className="text-sm italic text-accent">"{pressData.press_quote}"</p>
                  </Section>
                )}
                <div className="grid grid-cols-2 gap-4">
                  <Section title="Best Social Clip">
                    <p className="text-sm font-bold">{pressData.best_clip_timestamp}</p>
                    <p className="text-xs text-muted-foreground">{pressData.best_clip_reason}</p>
                  </Section>
                  <Section title="Contact">
                    <p className="text-sm font-medium">{pressData.contact_placeholder}</p>
                  </Section>
                </div>
                <Section title="Mood & Descriptors">
                  <TagCloud tags={pressData.mood_tags} color="accent" />
                </Section>
                <Section title="Similar Artists">
                  <TagCloud tags={analysis.similar_artists || []} color="primary" />
                </Section>
                <div className="flex gap-3 pt-2">
                  <Button onClick={() => generatePressPDF(analysis, pressData)} className="gap-2">
                    <Download className="h-4 w-4" />Download PDF
                  </Button>
                  <Button variant="outline" onClick={generatePressSheet} disabled={generating} size="sm" className="gap-2">
                    <Sparkles className="h-3.5 w-3.5" />Regenerate
                  </Button>
                </div>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}