import { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, FileText, Edit3, Eye, CheckCircle2, Clock, X, Send, Trash2, Download, Copy, Check, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import moment from "moment";

const STATUS_META = {
  Draft:     { color: "text-muted-foreground", bg: "bg-secondary", icon: Edit3 },
  Sent:      { color: "text-chart-5",          bg: "bg-chart-5/10", icon: Send },
  Signed:    { color: "text-primary",          bg: "bg-primary/10", icon: CheckCircle2 },
  Cancelled: { color: "text-destructive",      bg: "bg-destructive/10", icon: X },
};

const PAYOUT_TYPES = ["Flat Fee", "Door Deal", "Guarantee + % of Door", "Revenue Share"];

// --- Contract Template ---
function buildContractBody(fields) {
  const {
    artist_name = "[ARTIST NAME]",
    venue_name = "[VENUE NAME]",
    performance_date = "[DATE]",
    performance_time = "[TIME]",
    soundcheck_time = "[SOUNDCHECK TIME]",
    set_length_minutes = "[SET LENGTH]",
    payout_amount = "[PAYOUT]",
    payout_structure = "Flat Fee",
    deposit_amount,
    technical_rider = "To be provided by artist.",
    hospitality_rider = "To be provided by artist.",
  } = fields;

  const dateStr = performance_date && performance_date !== "[DATE]"
    ? moment(performance_date).format("MMMM D, YYYY") : "[DATE]";

  return `PERFORMANCE AGREEMENT

This Performance Agreement ("Agreement") is entered into as of ${moment().format("MMMM D, YYYY")}, between:

ARTIST: ${artist_name}
VENUE:  ${venue_name}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. ENGAGEMENT

The Venue hereby engages the Artist to perform a live musical performance on the following terms:

  • Performance Date:    ${dateStr}
  • Doors / Show Time:  ${performance_time || "[TIME]"}
  • Soundcheck:         ${soundcheck_time || "[SOUNDCHECK TIME]"}
  • Set Length:         ${set_length_minutes} minutes

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2. COMPENSATION

  • Payout Structure:   ${payout_structure}
  • Total Guarantee:    $${Number(payout_amount || 0).toFixed(2)} USD
${deposit_amount ? `  • Deposit Due:        $${Number(deposit_amount).toFixed(2)} USD (payable upon signing)\n` : ""}  • Balance Due:        Payable on the night of performance, prior to Artist taking the stage.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

3. TECHNICAL RIDER

The Venue agrees to provide the following equipment and technical support:

${technical_rider}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

4. HOSPITALITY RIDER

The Venue agrees to provide the following hospitality:

${hospitality_rider}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

5. CANCELLATION POLICY

  • If the Venue cancels with less than 14 days' notice, the full guarantee is owed to the Artist.
  • If the Artist cancels with less than 14 days' notice, any deposit paid must be returned within 7 business days.
  • Force majeure (natural disaster, government order) releases both parties without penalty.

6. PROMOTION

The Venue agrees to promote the event via social media, email list, and in-house marketing channels no less than 14 days prior to the event date.

7. SOUND & PRODUCTION

The Venue agrees to provide a professional sound system and sound engineer for the duration of soundcheck and performance. The Artist's sound engineer (if any) shall have final authority over the front-of-house mix during the performance.

8. MERCHANDISE

The Artist retains 100% of merchandise sales at this event unless otherwise negotiated in writing prior to the event.

9. RECORDING

No audio or video recording of the Artist's performance may be made by the Venue without prior written consent from the Artist.

10. GOVERNING LAW

This Agreement shall be governed by and construed in accordance with applicable law. Any disputes shall be resolved through good-faith negotiation before pursuing legal remedies.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURES

By signing below, both parties agree to the terms of this Agreement.


ARTIST: ___________________________________   Date: ________________
         ${artist_name}


VENUE:  ___________________________________   Date: ________________
         ${venue_name}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SoundReady · soundready.app
`;
}

// --- Contract Editor ---
function ContractEditor({ contract, venues, onSave, onClose }) {
  const [form, setForm] = useState({
    venue_id: contract?.venue_id || "",
    venue_name: contract?.venue_name || "",
    artist_name: contract?.artist_name || "",
    performance_date: contract?.performance_date || "",
    performance_time: contract?.performance_time || "",
    soundcheck_time: contract?.soundcheck_time || "",
    set_length_minutes: contract?.set_length_minutes || "45",
    payout_amount: contract?.payout_amount || "",
    payout_structure: contract?.payout_structure || "Flat Fee",
    deposit_amount: contract?.deposit_amount || "",
    technical_rider: contract?.technical_rider || "• PA system (minimum 1000W)\n• Monitor wedge x2\n• DI box x2\n• Drum kit (if applicable)\n• Stage lighting",
    hospitality_rider: contract?.hospitality_rider || "• Bottled water (6 bottles)\n• Meal for each band member\n• Parking for 1 vehicle",
    status: contract?.status || "Draft",
    notes: contract?.notes || "",
  });
  const [preview, setPreview] = useState(false);
  const [copied, setCopied] = useState(false);

  const set = (k) => (e) => {
    const val = e.target.value;
    if (k === "venue_id") {
      const v = venues.find(x => x.id === val);
      setForm(f => ({ ...f, venue_id: val, venue_name: v?.name || f.venue_name, performance_date: v?.performance_date || f.performance_date }));
    } else {
      setForm(f => ({ ...f, [k]: val }));
    }
  };

  const contractText = buildContractBody(form);

  const handleSave = () => {
    onSave({ ...form, contract_body: contractText, payout_amount: Number(form.payout_amount || 0), deposit_amount: Number(form.deposit_amount || 0), set_length_minutes: Number(form.set_length_minutes || 0) });
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(contractText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([contractText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `contract-${form.venue_name.replace(/\s+/g, "-").toLowerCase()}-${form.performance_date || "draft"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-start justify-center overflow-y-auto p-4 py-8">
      <motion.div initial={{ opacity: 0, scale: 0.97 }} animate={{ opacity: 1, scale: 1 }}
        className="w-full max-w-4xl bg-card border border-border rounded-2xl shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border">
          <p className="font-heading font-bold text-lg">
            {contract ? "Edit Contract" : "New Contract"} {form.venue_name && `— ${form.venue_name}`}
          </p>
          <div className="flex items-center gap-2">
            <button onClick={() => setPreview(v => !v)}
              className={`h-8 px-3 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 ${preview ? "bg-primary/10 text-primary" : "bg-secondary text-muted-foreground hover:text-foreground"}`}>
              <Eye className="h-3.5 w-3.5" />{preview ? "Edit" : "Preview"}
            </button>
            <button onClick={onClose}><X className="h-5 w-5 text-muted-foreground" /></button>
          </div>
        </div>

        <div className="flex flex-col lg:flex-row min-h-0">
          {/* Form panel */}
          {!preview && (
            <div className="flex-1 p-5 space-y-4 overflow-y-auto lg:max-h-[75vh]">
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Artist Name *</label>
                  <Input value={form.artist_name} onChange={set("artist_name")} placeholder="Your artist name" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Link to Venue</label>
                  <select value={form.venue_id} onChange={set("venue_id")} className="w-full h-9 rounded-md border border-input bg-transparent px-3 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring">
                    <option value="">Enter manually</option>
                    {venues.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}
                  </select>
                </div>
                {!form.venue_id && (
                  <div className="space-y-1.5 col-span-2">
                    <label className="text-xs text-muted-foreground font-medium">Venue Name *</label>
                    <Input value={form.venue_name} onChange={set("venue_name")} placeholder="Venue name" />
                  </div>
                )}
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Performance Date</label>
                  <Input type="date" value={form.performance_date} onChange={set("performance_date")} />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Show Time</label>
                  <Input value={form.performance_time} onChange={set("performance_time")} placeholder="9:00 PM" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Soundcheck Time</label>
                  <Input value={form.soundcheck_time} onChange={set("soundcheck_time")} placeholder="6:00 PM" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Set Length (minutes)</label>
                  <Input type="number" value={form.set_length_minutes} onChange={set("set_length_minutes")} placeholder="45" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Payout Structure</label>
                  <select value={form.payout_structure} onChange={set("payout_structure")} className="w-full h-9 rounded-md border border-input bg-transparent px-3 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring">
                    {PAYOUT_TYPES.map(p => <option key={p}>{p}</option>)}
                  </select>
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Guarantee / Payout ($)</label>
                  <Input type="number" value={form.payout_amount} onChange={set("payout_amount")} placeholder="300.00" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Deposit Amount ($)</label>
                  <Input type="number" value={form.deposit_amount} onChange={set("deposit_amount")} placeholder="0.00" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs text-muted-foreground font-medium">Status</label>
                  <select value={form.status} onChange={set("status")} className="w-full h-9 rounded-md border border-input bg-transparent px-3 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring">
                    {["Draft", "Sent", "Signed", "Cancelled"].map(s => <option key={s}>{s}</option>)}
                  </select>
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs text-muted-foreground font-medium">Technical Rider</label>
                <textarea value={form.technical_rider} onChange={set("technical_rider")} rows={4}
                  className="w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring resize-none font-mono" />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs text-muted-foreground font-medium">Hospitality Rider</label>
                <textarea value={form.hospitality_rider} onChange={set("hospitality_rider")} rows={3}
                  className="w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring resize-none font-mono" />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs text-muted-foreground font-medium">Internal Notes</label>
                <Input value={form.notes} onChange={set("notes")} placeholder="Private notes (not in contract)" />
              </div>
            </div>
          )}

          {/* Preview panel */}
          {preview && (
            <div className="flex-1 p-5 overflow-y-auto lg:max-h-[75vh]">
              <pre className="text-xs text-foreground/85 font-mono whitespace-pre-wrap leading-relaxed bg-secondary/20 rounded-xl p-4 border border-border">
                {contractText}
              </pre>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-3 p-5 border-t border-border flex-wrap">
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5">
              {copied ? <><Check className="h-3.5 w-3.5" />Copied!</> : <><Copy className="h-3.5 w-3.5" />Copy Text</>}
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5">
              <Download className="h-3.5 w-3.5" />Download .txt
            </Button>
          </div>
          <div className="flex gap-2">
            <Button variant="ghost" onClick={onClose}>Cancel</Button>
            <Button onClick={handleSave} className="gap-2"><FileText className="h-4 w-4" />Save Contract</Button>
          </div>
        </div>
      </motion.div>
    </div>
  );
}

// --- Contract Card ---
function ContractCard({ contract, onEdit, onDelete, onStatusChange }) {
  const meta = STATUS_META[contract.status] || STATUS_META.Draft;
  const Icon = meta.icon;

  return (
    <div className="rounded-2xl bg-card border border-border p-5 flex items-start justify-between gap-4">
      <div className="flex items-start gap-4 min-w-0">
        <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
          <FileText className="h-5 w-5 text-primary" />
        </div>
        <div className="min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <p className="font-heading font-bold">{contract.venue_name}</p>
            <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold ${meta.bg} ${meta.color}`}>
              <Icon className="h-2.5 w-2.5" />{contract.status}
            </span>
          </div>
          <p className="text-sm text-muted-foreground mt-0.5">
            {contract.artist_name}
            {contract.performance_date && ` · ${moment(contract.performance_date).format("MMM D, YYYY")}`}
            {contract.payout_amount > 0 && ` · $${Number(contract.payout_amount).toFixed(0)} ${contract.payout_structure}`}
          </p>
          {contract.set_length_minutes > 0 && (
            <p className="text-xs text-muted-foreground mt-0.5">
              {contract.performance_time && `Show: ${contract.performance_time}`}
              {contract.soundcheck_time && ` · Soundcheck: ${contract.soundcheck_time}`}
              {` · ${contract.set_length_minutes} min set`}
            </p>
          )}
        </div>
      </div>
      <div className="flex items-center gap-1.5 shrink-0">
        {contract.status === "Draft" && (
          <button onClick={() => onStatusChange(contract, "Sent")}
            className="h-8 px-2.5 rounded-lg bg-chart-5/10 text-chart-5 text-xs font-medium hover:bg-chart-5/20 transition-colors flex items-center gap-1">
            <Send className="h-3 w-3" />Send
          </button>
        )}
        {contract.status === "Sent" && (
          <button onClick={() => onStatusChange(contract, "Signed")}
            className="h-8 px-2.5 rounded-lg bg-primary/10 text-primary text-xs font-medium hover:bg-primary/20 transition-colors flex items-center gap-1">
            <CheckCircle2 className="h-3 w-3" />Mark Signed
          </button>
        )}
        <button onClick={() => onEdit(contract)} className="h-8 w-8 rounded-lg hover:bg-secondary flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors">
          <Edit3 className="h-3.5 w-3.5" />
        </button>
        <button onClick={() => onDelete(contract.id)} className="h-8 w-8 rounded-lg hover:bg-destructive/10 flex items-center justify-center text-muted-foreground hover:text-destructive transition-colors">
          <Trash2 className="h-3.5 w-3.5" />
        </button>
      </div>
    </div>
  );
}

// --- Main Page ---
export default function VenueContracts() {
  const [contracts, setContracts] = useState([]);
  const [venues, setVenues] = useState([]);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(null); // null = closed, false = new, object = edit
  const [filter, setFilter] = useState("All");

  useEffect(() => {
    Promise.all([
      base44.entities.VenueContract.list("-created_date", 100),
      base44.entities.Venue.list("-created_date", 200),
    ]).then(([c, v]) => {
      setContracts(c);
      setVenues(v);
      setLoading(false);
    });
  }, []);

  const handleSave = async (data) => {
    if (editing && editing.id) {
      const updated = await base44.entities.VenueContract.update(editing.id, data);
      setContracts(prev => prev.map(c => c.id === editing.id ? updated : c));
    } else {
      const created = await base44.entities.VenueContract.create(data);
      setContracts(prev => [created, ...prev]);
    }
    setEditing(null);
  };

  const handleDelete = async (id) => {
    await base44.entities.VenueContract.delete(id);
    setContracts(prev => prev.filter(c => c.id !== id));
  };

  const handleStatusChange = async (contract, status) => {
    const updated = await base44.entities.VenueContract.update(contract.id, { status });
    setContracts(prev => prev.map(c => c.id === contract.id ? { ...c, status } : c));
  };

  const statusCounts = ["Draft", "Sent", "Signed", "Cancelled"].reduce((acc, s) => {
    acc[s] = contracts.filter(c => c.status === s).length;
    return acc;
  }, {});

  const filtered = filter === "All" ? contracts : contracts.filter(c => c.status === filter);

  return (
    <div className="min-h-screen bg-background px-4 py-10">
      {editing !== null && (
        <ContractEditor
          contract={editing || null}
          venues={venues}
          onSave={handleSave}
          onClose={() => setEditing(null)}
        />
      )}

      <div className="max-w-4xl mx-auto space-y-6">
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs text-primary uppercase tracking-widest font-medium">Touring</p>
            <h1 className="font-heading text-4xl font-bold">Venue Contracts</h1>
            <p className="text-muted-foreground text-sm mt-1">Create, manage, and track performance agreements.</p>
          </div>
          <Button onClick={() => setEditing(false)} className="gap-2 shrink-0">
            <Plus className="h-4 w-4" />New Contract
          </Button>
        </motion.div>

        {/* Stats */}
        <div className="grid grid-cols-4 gap-3">
          {["Draft", "Sent", "Signed", "Cancelled"].map(s => {
            const m = STATUS_META[s];
            const SIcon = m.icon;
            return (
              <button key={s} onClick={() => setFilter(filter === s ? "All" : s)}
                className={`rounded-2xl border p-4 text-center transition-all ${filter === s ? `${m.bg} border-current` : "bg-card border-border hover:border-border/80"}`}>
                <SIcon className={`h-4 w-4 mx-auto mb-1 ${m.color}`} />
                <p className={`font-heading font-bold text-xl ${m.color}`}>{statusCounts[s] || 0}</p>
                <p className="text-xs text-muted-foreground">{s}</p>
              </button>
            );
          })}
        </div>

        {loading ? (
          <div className="flex justify-center py-20">
            <div className="h-6 w-6 border-2 border-primary/20 border-t-primary rounded-full animate-spin" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-20 space-y-3">
            <FileText className="h-12 w-12 text-muted-foreground/30 mx-auto" />
            <p className="text-muted-foreground text-sm">
              {filter === "All" ? "No contracts yet. Create your first performance agreement." : `No ${filter} contracts.`}
            </p>
            {filter === "All" && <Button onClick={() => setEditing(false)}>Create First Contract</Button>}
          </div>
        ) : (
          <div className="space-y-3">
            {filtered.map(c => (
              <ContractCard key={c.id} contract={c}
                onEdit={setEditing}
                onDelete={handleDelete}
                onStatusChange={handleStatusChange}
              />
            ))}
          </div>
        )}

        {/* Tips */}
        <div className="rounded-2xl bg-card border border-border p-5 space-y-3">
          <p className="font-heading font-semibold text-sm flex items-center gap-2">
            <AlertCircle className="h-4 w-4 text-chart-5" />Contract Tips
          </p>
          <ul className="text-xs text-muted-foreground space-y-1.5 list-disc list-inside">
            <li>Always get a signed contract before confirming a show date publicly</li>
            <li>Request a deposit (typically 50%) to lock in the booking</li>
            <li>Send your technical rider at least 2 weeks before the show</li>
            <li>Download as .txt and paste into a signing tool like DocuSign or HelloSign</li>
            <li>Keep a copy of every signed contract in cloud storage</li>
          </ul>
        </div>
      </div>
    </div>
  );
}